sonar.projectKey=retiradas
sonar.projectName=Retiradas
sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN}
sonar.sources=src
sonar.exclusions=node_modules/**,deploy-*/**,package-*/**,vps/**,build/**,dist/**,coverage/**,public/**,tmp/**,.scannerwork/**,.nyc_output/**,uploads/**,output/**,outputs/**
