sonar.projectKey=retiradas
sonar.projectName=Retiradas
sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN}
sonar.sources=apps/retiradas/frontend/src,apps/retiradas/backend/api,apps/retiradas/backend/scripts
sonar.tests=apps/retiradas/frontend/src,apps/retiradas/backend/api,apps/retiradas/backend/scripts
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.mjs,apps/retiradas/frontend/tests/e2e/**
sonar.exclusions=node_modules/**,deploy-*/**,package-*/**,apps/finan/**,apps/adm/**,apps/operacao/**,build/**,dist/**,coverage/**,apps/retiradas/frontend/public/**,tmp/**,.scannerwork/**,.nyc_output/**,uploads/**,output/**,outputs/**,apps/retiradas/backend/node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
