export const COLLECTIONS = {
	USUARIOS: "usuarios",
	COLABORADORES: "colaboradores",
	FERIAS: "ferias",
	FERIADOS: "feriados",
	ACTIVITY_LOG: "activity_log",
	ATESTADOS: "atestados",
	EQUIPAMENTOS: "equipamentos",
	REGIONAIS: "regionais",
	AGENTES: "agentes",
	AGENDA: "agenda",
	AGENDAMENTOS: "agendamentos",
	AGENDAMENTOS_LOGS: "agendamentos_logs",
	ACOMPANHAMENTO_DIARIO: "acompanhamento_diario",
	ACOMPANHAMENTO_DIARIO_LOGS: "acompanhamento_diario_logs",
	ACOMPANHAMENTO_DIARIO_METAS_HISTORICO:
		"acompanhamento_diario_metas_historico",
	VISITAS: "visitas",
	VISITAS_TECNICOS: "visitas_tecnicos",
	VISITAS_CONFIG: "visitas_config",
	DUVIDAS_RETIRADA: "duvidas_retirada",
	RETIRADAS_SOLICITACOES: "retiradas_solicitacoes",
	INTEGRACOES_API: "integracoes_api",
	HUBSOFT_ORDENS_SERVICO: "hubsoft_ordens_servico",
	INSUMOS_ADMINISTRATIVOS_PRODUTOS: "insumos_administrativos_produtos",
	INSUMOS_ADMINISTRATIVOS_RETIRADAS: "insumos_administrativos_retiradas",
	INSUMOS_ADMINISTRATIVOS_REPOSICOES: "insumos_administrativos_reposicoes",
	INSUMOS_ADMINISTRATIVOS_REQUISICOES: "insumos_administrativos_requisicoes",
	INSUMOS_ADMINISTRATIVOS_CONFIG: "insumos_administrativos_config",
	PLAYGROUND_MOVIMENTACOES: "playground_movimentacoes",
	EMPRESAS_TECNICOS: "empresas_tecnicos",
	ACERTO_ESTOQUE_EMPRESAS: "acerto_estoque_empresas",
	ACERTO_ESTOQUE_TECNICOS: "acerto_estoque_tecnicos",
	ACERTO_ESTOQUE_ACERTOS: "acerto_estoque_acertos",
	ENTREGAS_TECNICOS: "entregas_tecnicos",
	VALIDACOES_ENTREGAS: "validacoes_entregas",
	COMPETENCIAS_ENTREGAS: "competencias_entregas",
	ENTREGAS_TECNICOS_CONFIG: "entregas_tecnicos_config",
	MENSAGERIA_CONFIG: "mensageria_config",
	MENSAGERIA_TEMPLATES: "mensageria_templates",
	MENSAGERIA_FILA: "mensageria_fila",
	MENSAGERIA_HISTORICO: "mensageria_historico",
	MENSAGERIA_CALLBACKS: "mensageria_callbacks",
	LOGISTICA_PONTOS: "logistica_pontos",
	LOGISTICA_COTACOES: "logistica_cotacoes",
	LOGISTICA_CONFIG: "logistica_config",
};
