export const COLLECTIONS = {
  USUARIOS:        'usuarios',
  COLABORADORES:   'colaboradores',
  FERIAS:          'ferias',
  VEICULOS:        'veiculos',
  CHECKLISTS:      'checklists',
  ABASTECIMENTOS:  'abastecimentos',
  FROTA_MULTAS:    'frota_multas',
  FROTA_SINISTROS: 'frota_sinistros',
  FERIADOS:        'feriados',
  ACTIVITY_LOG:    'activity_log',
  PRESENCAS:       'presencas',
  ATESTADOS:       'atestados',
  COMISSOES:       'comissoes',
  COMISSAO_CONFIG: 'comissao_config',
  BANCO_HORAS:     'banco_horas',
  EQUIPAMENTOS:    'equipamentos',
  REGIONAIS:       'regionais',
  AGENTES:         'agentes',
  AGENDA:          'agenda',
  DUVIDAS_RETIRADA: 'duvidas_retirada',
  ANALISES_PROJECAO: 'analises_projecao',
  MAPEAMENTO_REGIONAIS: 'mapeamento_regionais',
  MAPEAMENTO_DASHBOARD: 'mapeamento_dashboard',
};
