export const ROUTES = {
	LOGIN: "/login",
	FORGOT_PASSWORD: "/esqueci-senha",
	RESET_PASSWORD: "/redefinir-senha",
	ACCESS_DENIED: "/acesso-negado",

	DASHBOARD: "/",
	DIARIO: "/diario",
	ACERTO_ESTOQUE: "/acerto-estoque",
	ESTOQUE_INTEGRADO: "/estoque",
	ESTOQUE_EQUIPAMENTOS: "/estoque/equipamentos",
	ESTOQUE_BOLSA_TECNICO: "/estoque/bolsa-tecnico",
	TECNICOS_AUDITORIA_BOLSA: "/tecnicos/auditoria/bolsa-tecnico",
	TECNICOS_AUDITORIA_RELATORIOS: "/tecnicos/auditoria/relatorios",
	ESTOQUE_CONSULTA: "/estoque/consulta",
	FERIAS: "/ferias",
	ATESTADOS: "/atestados",
	FERIADOS: "/feriados",
	USUARIOS: "/usuarios",
	CARGOS_PERMISSOES: "/configuracoes/cargos",
	COLABORADORES: "/colaboradores",
	EQUIPAMENTOS: "/equipamentos",
	REGIONAIS: "/regionais",
	AGENTES: "/agentes",
	AGENDA: "/agenda",
	AGENDAMENTOS: "/agendamentos",
	ACOMPANHAMENTO: "/acompanhamento",
	ACOMPANHAMENTO_FINANCEIRO: "/acompanhamento/financeiro",
	VISITAS: "/visitas",
	GESTAO_DUVIDAS: "/gestao-duvidas",
	METAS: "/metas",
	NOTIFICACOES: "/notificacoes",
	RETIRADAS: "/retiradas",
	ENTREGAS_TECNICOS: "/entregas-tecnicos",
	LOGISTICA: "/logistica",
	FINANCEIRO: "/financeiro",
	FINANCEIRO_CONTAS_PAGAR: "/financeiro/contas-a-pagar",
	FINANCEIRO_CONTAS_RECEBER: "/financeiro/contas-a-receber",
	FINANCEIRO_FATURAMENTO: "/financeiro/faturamento",
	FINANCEIRO_NOTAS: "/financeiro/notas",
	FINANCEIRO_REPORTS_SERASA: "/financeiro/reports/serasa",
	FINANCEIRO_REPORTS_TARIFAS: "/financeiro/reports/tarifas",
	FINANCEIRO_REPORTS_TARIFAS_FATURAS: "/financeiro/reports/tarifas/faturas",
	FINANCEIRO_REPORTS_TARIFAS_REC_CLIENTE:
		"/financeiro/reports/tarifas/rec-cliente",
	FINANCEIRO_REPORTS_TARIFAS_FORMAS_PAGAMENTO:
		"/financeiro/reports/tarifas/formas-pagamento",
	FINANCEIRO_GESTAO_ORCAMENTO: "/financeiro/gestao-orcamento",
	FINANCEIRO_ORCAMENTO_DADOS: "/financeiro/gestao-orcamento/dados",
	FINANCEIRO_ORCAMENTO_CENTROS_CUSTO:
		"/financeiro/gestao-orcamento/centros-custo",
	FINANCEIRO_ORCAMENTO_DRE: "/financeiro/gestao-orcamento/dre",
	FINANCEIRO_ORCAMENTO_APROVACOES: "/financeiro/gestao-orcamento/aprovacoes",
	FINANCEIRO_ORCAMENTO_CONFIGURACOES:
		"/financeiro/gestao-orcamento/configuracoes",
	FINANCEIRO_CONFIGURACOES: "/financeiro/configuracoes",
	FINANCEIRO_EQUIPE: "/financeiro/equipe",
	ATENDIMENTO_CASOS: "/atendimento/casos",
	ATENDIMENTO_TECNICOS: "/atendimento/tecnicos",
	ATENDIMENTO_AVALIACOES: "/atendimento/avaliacoes",
	ATENDIMENTO_CONFIGURACOES: "/atendimento/configuracoes",
	ATENDIMENTO_TEMPLATES: "/atendimento/templates",
	ATENDIMENTO_LOGS: "/atendimento/logs",
	ATENDIMENTO_MENSAGENS: "/atendimento/mensagens",
	INTEGRACOES: "/integracoes",
	MENSAGERIA: "/mensageria",
	MENSAGERIA_API: "/mensageria/api",
	MENSAGERIA_FILA: "/mensageria/fila",
	MENSAGERIA_ENVIADOS: "/mensageria/enviados",
	MENSAGERIA_RELATORIOS: "/mensageria/relatorios",
	MENSAGERIA_CONFIRMACAO_AGENDAMENTOS: "/mensageria/confirmacao-agendamentos",
	MENSAGERIA_BACKLOG: "/mensageria/backlog",
	MENSAGERIA_CALLBACK: "/mensageria/callback",
	CONFIGURACOES_GERAIS: "/configuracoes/geral",
	API_STATUS: "/configuracoes/apis",
	HUBSOFT_SETTINGS: "/configuracoes/hubsoft",
	CVORTEX_SETTINGS: "/configuracoes/cvortex",
	SENIOR_SETTINGS: "/configuracoes/senior",
	DATABASE_BACKUPS: "/configuracoes/banco-de-dados",
	EMAIL_SETTINGS: "/configuracoes/email",
	VPN_SETTINGS: "/configuracoes/vpn",
	AUDITORIA_LOGS: "/logs",
	EMPRESAS_TECNICOS: "/empresas",
	EMPRESA_PERFIL: "/empresas/:slug",
	DOCUMENTOS_PENDENTES: "/documentos/pendentes",
	DOCUMENTOS_TRATATIVAS: "/documentos/tratativas",
	DOCUMENTOS_HISTORICO: "/documentos/historico",
	DOCUMENTOS_APROVADOS: "/documentos/aprovados",
	DOCUMENTOS_CONFIGURACAO: "/documentos/configuracao",
	DOCUMENTOS_RELATORIOS: "/documentos/relatorios",
	INSUMOS_ADMINISTRATIVOS: "/administrativo/insumos",
	INSUMOS_REQUISICOES: "/administrativo/insumos/requisicoes",
	IMOVEIS_ADMINISTRATIVOS: "/administrativo/imoveis",
	IMOVEL_ADMINISTRATIVO_DETALHE: "/administrativo/imoveis/:id",
	IMOVEIS_ADMINISTRATIVOS_CONTRATOS: "/administrativo/imoveis/contratos",
	IMOVEIS_ADMINISTRATIVOS_HISTORICO: "/administrativo/imoveis/historico",
	IMOVEIS_ADMINISTRATIVOS_RELATORIOS: "/administrativo/imoveis/relatorios",
	REGRAS: "/configuracoes/regras",
	RELATORIOS: "/relatorios",
	FERRAMENTAS: "/ferramentas",
	MAPA: "/mapa",
	MAPA_HISTORICO: "/mapa/historico",

	PAINEL_PUBLICO: "/painel",
	PAINEL_AGENTES: "/painel/agentes",
	PAINEL_RELATORIOS: "/painel/relatorios",
	DUVIDAS_PUBLICO: "/duvidas",
	DEVOLUCAO_PUBLICO: "/devolucao",
	PAINEL_MAPA: "/painel/mapa",
	PAINEL_MATCH: "/painel/match",
	AGENTES_MATCH_PUBLICO: "/aa-sempre",
	TERCEIROS: "/terceiros",
	TERCEIRIZADOS: "/terceirizados",
	TERCEIRIZADOS_LOGIN: "/terceirizados/login",
	TERCEIRIZADOS_CONSULTA_MAC: "/terceirizados/consulta-mac",
	TERCEIROS_CONSULTA_MAC: "/terceiros/consulta-mac",
};
