sonar.projectKey=finan
sonar.projectName=Finan
sonar.sources=frontend/src,backend/src,backend/scripts,shared
sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/public/**
sonar.sourceEncoding=UTF-8
