create table if not exists app_roles (
  id text primary key,
  name text not null,
  description text,
  system_role boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app_role_permissions (
  role_id text not null references app_roles(id) on delete cascade,
  permission text not null,
  created_at timestamptz not null default now(),
  primary key (role_id, permission)
);

drop trigger if exists app_roles_touch_updated_at on app_roles;
create trigger app_roles_touch_updated_at
before update on app_roles
for each row execute function touch_updated_at();

insert into app_roles (id, name, description, system_role, active)
values
  ('admin', 'Admin', 'Acesso total ao sistema.', true, true),
  ('backoffice_retirada', 'Backoffice Retirada', 'Operação de retiradas sem configurações sensíveis.', true, true),
  ('supervisor', 'Supervisor', 'Gestão operacional por regional.', true, true),
  ('supervisor_administrativo', 'Supervisor Administrativo', 'Gestão administrativa de documentos, empresas, usuários e insumos.', true, true),
  ('analista_administrativo', 'Analista Administrativo', 'Análise administrativa de documentos, empresas e insumos.', true, true),
  ('lider_empresa', 'Líder Empresa', 'Portal de empresa e documentos vinculados.', true, true),
  ('agente_autorizado', 'Agente Autorizado', 'Portal de agente autorizado e documentos vinculados.', true, true),
  ('backoffice', 'Backoffice', 'Acerto de estoque e dashboard básico.', true, true)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  system_role = true,
  active = true;

with defaults(role_id, permission) as (
  values
    ('admin', '*'),
    ('backoffice_retirada', 'view_dashboard'),
    ('backoffice_retirada', 'view_diario'),
    ('backoffice_retirada', 'view_acerto_estoque'),
    ('backoffice_retirada', 'manage_acerto_estoque'),
    ('backoffice_retirada', 'view_estoque_integrado'),
    ('backoffice_retirada', 'view_equipamentos'),
    ('backoffice_retirada', 'view_mapa'),
    ('backoffice_retirada', 'view_metas'),
    ('backoffice_retirada', 'view_cobrancas'),
    ('backoffice_retirada', 'view_relatorios'),
    ('backoffice_retirada', 'view_agenda'),
    ('backoffice_retirada', 'view_agendamentos'),
    ('backoffice_retirada', 'view_visitas'),
    ('backoffice_retirada', 'view_duvidas'),
    ('backoffice_retirada', 'view_retiradas'),
    ('backoffice_retirada', 'view_entregas_tecnicos'),
    ('backoffice_retirada', 'view_logistica'),
    ('backoffice_retirada', 'manage_logistica'),
    ('backoffice_retirada', 'view_ferramentas'),
    ('backoffice_retirada', 'view_regionais'),
    ('backoffice_retirada', 'view_agentes'),
    ('backoffice_retirada', 'request_ferias'),
    ('backoffice_retirada', 'manage_colaboradores'),
    ('backoffice_retirada', 'manage_metas'),
    ('backoffice_retirada', 'manage_cobrancas'),
    ('backoffice_retirada', 'manage_duvidas'),
    ('backoffice_retirada', 'manage_retiradas'),
    ('backoffice_retirada', 'manage_entregas_tecnicos'),
    ('backoffice_retirada', 'manage_feriados'),
    ('backoffice_retirada', 'manage_regionais'),
    ('backoffice_retirada', 'manage_agentes'),
    ('backoffice_retirada', 'manage_agenda'),
    ('backoffice_retirada', 'manage_agendamentos'),
    ('backoffice_retirada', 'manage_visitas'),
    ('backoffice_retirada', 'manage_equipamentos'),
    ('backoffice_retirada', 'manage_veiculos'),
    ('backoffice_retirada', 'view_mensageria'),
    ('backoffice_retirada', 'view_confirmacao_agendamentos'),
    ('backoffice_retirada', 'view_insumos_administrativos'),
    ('backoffice_retirada', 'manage_insumos_administrativos'),
    ('supervisor', 'view_dashboard'),
    ('supervisor', 'view_diario'),
    ('supervisor', 'view_acerto_estoque'),
    ('supervisor', 'manage_acerto_estoque'),
    ('supervisor', 'view_estoque_integrado'),
    ('supervisor', 'view_equipamentos'),
    ('supervisor', 'view_mapa'),
    ('supervisor', 'view_metas'),
    ('supervisor', 'view_cobrancas'),
    ('supervisor', 'view_relatorios'),
    ('supervisor', 'view_agenda'),
    ('supervisor', 'view_agendamentos'),
    ('supervisor', 'view_visitas'),
    ('supervisor', 'view_duvidas'),
    ('supervisor', 'view_retiradas'),
    ('supervisor', 'view_entregas_tecnicos'),
    ('supervisor', 'view_logistica'),
    ('supervisor', 'manage_logistica'),
    ('supervisor', 'view_empresas_tecnicos'),
    ('supervisor', 'manage_empresas_tecnicos'),
    ('supervisor', 'view_documentos'),
    ('supervisor', 'view_documentos_tratativas'),
    ('supervisor', 'view_ferramentas'),
    ('supervisor', 'view_regionais'),
    ('supervisor', 'view_agentes'),
    ('supervisor', 'request_ferias'),
    ('supervisor', 'manage_colaboradores'),
    ('supervisor', 'manage_metas'),
    ('supervisor', 'manage_cobrancas'),
    ('supervisor', 'manage_duvidas'),
    ('supervisor', 'manage_retiradas'),
    ('supervisor', 'manage_entregas_tecnicos'),
    ('supervisor', 'manage_feriados'),
    ('supervisor', 'manage_regionais'),
    ('supervisor', 'manage_agentes'),
    ('supervisor', 'manage_agenda'),
    ('supervisor', 'manage_agendamentos'),
    ('supervisor', 'manage_visitas'),
    ('supervisor', 'manage_equipamentos'),
    ('supervisor', 'manage_veiculos'),
    ('supervisor', 'view_mensageria'),
    ('supervisor', 'view_confirmacao_agendamentos'),
    ('supervisor', 'manage_users'),
    ('supervisor', 'manage_general_settings'),
    ('supervisor', 'view_insumos_administrativos'),
    ('supervisor', 'manage_insumos_administrativos'),
    ('supervisor_administrativo', 'view_dashboard'),
    ('supervisor_administrativo', 'view_empresas_tecnicos'),
    ('supervisor_administrativo', 'manage_empresas_tecnicos'),
    ('supervisor_administrativo', 'view_documentos'),
    ('supervisor_administrativo', 'view_documentos_tratativas'),
    ('supervisor_administrativo', 'manage_documentos'),
    ('supervisor_administrativo', 'view_documentos_relatorios'),
    ('supervisor_administrativo', 'view_insumos_administrativos'),
    ('supervisor_administrativo', 'manage_insumos_administrativos'),
    ('supervisor_administrativo', 'manage_general_settings'),
    ('supervisor_administrativo', 'manage_users'),
    ('supervisor_administrativo', 'manage_roles'),
    ('analista_administrativo', 'view_dashboard'),
    ('analista_administrativo', 'view_empresas_tecnicos'),
    ('analista_administrativo', 'manage_empresas_tecnicos'),
    ('analista_administrativo', 'view_documentos'),
    ('analista_administrativo', 'view_documentos_tratativas'),
    ('analista_administrativo', 'view_documentos_relatorios'),
    ('analista_administrativo', 'view_insumos_administrativos'),
    ('analista_administrativo', 'manage_insumos_administrativos'),
    ('lider_empresa', 'view_dashboard'),
    ('lider_empresa', 'view_empresas_tecnicos'),
    ('lider_empresa', 'view_documentos'),
    ('agente_autorizado', 'view_empresas_tecnicos'),
    ('agente_autorizado', 'view_documentos'),
    ('backoffice', 'view_dashboard'),
    ('backoffice', 'view_acerto_estoque'),
    ('backoffice', 'manage_acerto_estoque')
)
insert into app_role_permissions (role_id, permission)
select role_id, permission
from defaults
on conflict do nothing;
