create table if not exists app_permissions (
  id text primary key,
  section_id text not null,
  section_label text not null,
  feature_id text not null,
  feature_label text not null,
  action text not null check (action in ('view', 'manage')),
  description text,
  sort_order integer not null default 0,
  active boolean not null default true,
  deprecated boolean not null default false,
  legacy_permission text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists app_permissions_touch_updated_at on app_permissions;
create trigger app_permissions_touch_updated_at
before update on app_permissions
for each row execute function touch_updated_at();

with permissions(id, section_id, section_label, feature_id, feature_label, action, sort_order, legacy_permission, description) as (
  values
    ('destaque.dashboard.view', 'destaque', 'Destaque', 'dashboard', 'Dashboard', 'view', 100, 'view_dashboard', 'Visualizar dashboard principal.'),
    ('destaque.diario.view', 'destaque', 'Destaque', 'diario', 'Diário', 'view', 110, 'view_diario', 'Visualizar Diário.'),
    ('destaque.diario.manage', 'destaque', 'Destaque', 'diario', 'Diário', 'manage', 111, null, 'Gerenciar lançamentos do Diário.'),
    ('destaque.mapa_os.view', 'destaque', 'Destaque', 'mapa_os', 'Mapa O.S', 'view', 120, 'view_mapa', 'Visualizar Mapa O.S.'),
    ('destaque.metas.view', 'destaque', 'Destaque', 'metas', 'Metas', 'view', 130, 'view_metas', 'Visualizar Metas.'),
    ('destaque.metas.manage', 'destaque', 'Destaque', 'metas', 'Metas', 'manage', 131, 'manage_metas', 'Gerenciar Metas.'),

    ('empresas.cadastro.view', 'empresas', 'Empresas', 'cadastro', 'Cadastro', 'view', 200, 'view_empresas_tecnicos', 'Visualizar empresas e técnicos.'),
    ('empresas.cadastro.manage', 'empresas', 'Empresas', 'cadastro', 'Cadastro', 'manage', 201, 'manage_empresas_tecnicos', 'Gerenciar empresas e técnicos.'),

    ('cliente.agendamentos.view', 'cliente', 'Cliente', 'agendamentos', 'Agendamentos', 'view', 300, 'view_agendamentos', 'Visualizar agendamentos.'),
    ('cliente.agendamentos.manage', 'cliente', 'Cliente', 'agendamentos', 'Agendamentos', 'manage', 301, 'manage_agendamentos', 'Gerenciar agendamentos.'),

    ('tecnicos.entrega_tecnicos.view', 'tecnicos', 'Técnicos', 'entrega_tecnicos', 'Entrega dos Técnicos', 'view', 400, 'view_entregas_tecnicos', 'Visualizar entrega dos técnicos.'),
    ('tecnicos.entrega_tecnicos.manage', 'tecnicos', 'Técnicos', 'entrega_tecnicos', 'Entrega dos Técnicos', 'manage', 401, 'manage_entregas_tecnicos', 'Gerenciar entrega dos técnicos.'),
    ('tecnicos.bolsa_tecnico.view', 'tecnicos', 'Técnicos', 'bolsa_tecnico', 'Bolsa Técnico', 'view', 410, 'view_estoque_integrado', 'Visualizar Bolsa Técnico.'),
    ('tecnicos.bolsa_tecnico.manage', 'tecnicos', 'Técnicos', 'bolsa_tecnico', 'Bolsa Técnico', 'manage', 411, null, 'Gerenciar Bolsa Técnico.'),

    ('logistica.logistica.view', 'logistica', 'Logística', 'logistica', 'Logística', 'view', 500, 'view_logistica', 'Visualizar Logística.'),
    ('logistica.logistica.manage', 'logistica', 'Logística', 'logistica', 'Logística', 'manage', 501, 'manage_logistica', 'Gerenciar Logística.'),

    ('estoque.equipamentos.view', 'estoque', 'Estoque', 'equipamentos', 'Equipamentos', 'view', 600, 'view_estoque_integrado', 'Visualizar Equipamentos.'),
    ('estoque.equipamentos.manage', 'estoque', 'Estoque', 'equipamentos', 'Equipamentos', 'manage', 601, 'manage_equipamentos', 'Gerenciar Equipamentos.'),
    ('estoque.consulta.view', 'estoque', 'Estoque', 'consulta', 'Consulta', 'view', 610, 'view_estoque_integrado', 'Consultar estoque.'),
    ('estoque.acerto_estoque.view', 'estoque', 'Estoque', 'acerto_estoque', 'Acerto de Estoque', 'view', 620, 'view_acerto_estoque', 'Visualizar acerto de estoque.'),
    ('estoque.acerto_estoque.manage', 'estoque', 'Estoque', 'acerto_estoque', 'Acerto de Estoque', 'manage', 621, 'manage_acerto_estoque', 'Gerenciar acerto de estoque.'),

    ('administrativo.documentos.view', 'administrativo', 'Administrativo', 'documentos', 'Documentos', 'view', 700, 'view_documentos', 'Visualizar documentos, pendentes, histórico, aprovados e tratativas.'),
    ('administrativo.documentos.manage', 'administrativo', 'Administrativo', 'documentos', 'Documentos', 'manage', 701, 'manage_documentos', 'Gerenciar regras e aprovações de documentos.'),
    ('administrativo.insumos.view', 'administrativo', 'Administrativo', 'insumos', 'Insumos', 'view', 710, 'view_insumos_administrativos', 'Visualizar insumos e requisições.'),
    ('administrativo.insumos.manage', 'administrativo', 'Administrativo', 'insumos', 'Insumos', 'manage', 711, 'manage_insumos_administrativos', 'Gerenciar insumos e requisições.'),
    ('administrativo.imoveis.view', 'administrativo', 'Administrativo', 'imoveis', 'Imóveis', 'view', 720, 'view_imoveis_administrativos', 'Visualizar imóveis administrativos.'),
    ('administrativo.imoveis.manage', 'administrativo', 'Administrativo', 'imoveis', 'Imóveis', 'manage', 721, 'manage_imoveis_administrativos', 'Gerenciar imóveis administrativos.'),
    ('administrativo.relatorios.view', 'administrativo', 'Administrativo', 'relatorios', 'Relatórios', 'view', 730, 'view_documentos_relatorios', 'Visualizar relatórios administrativos.'),

    ('equipe.colaboradores.view', 'equipe', 'Equipe', 'colaboradores', 'Colaboradores', 'view', 800, 'manage_colaboradores', 'Visualizar colaboradores.'),
    ('equipe.colaboradores.manage', 'equipe', 'Equipe', 'colaboradores', 'Colaboradores', 'manage', 801, 'manage_colaboradores', 'Gerenciar colaboradores.'),
    ('equipe.agenda.view', 'equipe', 'Equipe', 'agenda', 'Agenda da Equipe', 'view', 810, 'view_agenda', 'Visualizar agenda da equipe.'),
    ('equipe.agenda.manage', 'equipe', 'Equipe', 'agenda', 'Agenda da Equipe', 'manage', 811, 'manage_agenda', 'Gerenciar agenda da equipe.'),
    ('equipe.feriados.view', 'equipe', 'Equipe', 'feriados', 'Feriados', 'view', 820, 'manage_feriados', 'Visualizar feriados.'),
    ('equipe.feriados.manage', 'equipe', 'Equipe', 'feriados', 'Feriados', 'manage', 821, 'manage_feriados', 'Gerenciar feriados.'),
    ('equipe.ferias.view', 'equipe', 'Equipe', 'ferias', 'Férias', 'view', 830, 'request_ferias', 'Visualizar férias.'),
    ('equipe.ferias.manage', 'equipe', 'Equipe', 'ferias', 'Férias', 'manage', 831, 'approve_ferias', 'Gerenciar férias.'),

    ('mensageria.enviados.view', 'mensageria', 'Mensageria', 'enviados', 'Enviados', 'view', 900, 'view_mensageria', 'Visualizar mensagens enviadas.'),
    ('mensageria.relatorios.view', 'mensageria', 'Mensageria', 'relatorios', 'Relatórios', 'view', 910, 'view_mensageria_relatorios', 'Visualizar relatórios de mensageria.'),
    ('mensageria.confirmacao_agendamentos.view', 'mensageria', 'Mensageria', 'confirmacao_agendamentos', 'Confirmação de Agendamento', 'view', 920, 'view_confirmacao_agendamentos', 'Visualizar confirmação de agendamentos.'),
    ('mensageria.confirmacao_agendamentos.manage', 'mensageria', 'Mensageria', 'confirmacao_agendamentos', 'Confirmação de Agendamento', 'manage', 921, 'manage_confirmacao_agendamentos', 'Gerenciar confirmação de agendamentos.'),
    ('mensageria.fila.view', 'mensageria', 'Mensageria', 'fila', 'Fila', 'view', 930, 'manage_mensageria', 'Visualizar fila de mensageria.'),
    ('mensageria.fila.manage', 'mensageria', 'Mensageria', 'fila', 'Fila', 'manage', 931, 'manage_mensageria', 'Gerenciar fila de mensageria.'),
    ('mensageria.backlog.view', 'mensageria', 'Mensageria', 'backlog', 'Backlog', 'view', 940, 'manage_mensageria', 'Visualizar backlog de mensageria.'),
    ('mensageria.backlog.manage', 'mensageria', 'Mensageria', 'backlog', 'Backlog', 'manage', 941, 'manage_mensageria', 'Gerenciar backlog de mensageria.'),
    ('mensageria.callback.view', 'mensageria', 'Mensageria', 'callback', 'Callback', 'view', 950, 'manage_mensageria', 'Visualizar callbacks de mensageria.'),
    ('mensageria.callback.manage', 'mensageria', 'Mensageria', 'callback', 'Callback', 'manage', 951, 'manage_mensageria', 'Gerenciar callbacks de mensageria.'),
    ('mensageria.api.view', 'mensageria', 'Mensageria', 'api', 'API', 'view', 960, 'manage_mensageria', 'Visualizar API de mensageria.'),
    ('mensageria.api.manage', 'mensageria', 'Mensageria', 'api', 'API', 'manage', 961, 'manage_mensageria', 'Gerenciar API de mensageria.'),
    ('mensageria.email_config.view', 'mensageria', 'Mensageria', 'email_config', 'Configurações de E-mail', 'view', 970, 'manage_mensageria', 'Visualizar configurações de envio.'),
    ('mensageria.email_config.manage', 'mensageria', 'Mensageria', 'email_config', 'Configurações de E-mail', 'manage', 971, 'manage_mensageria', 'Gerenciar configurações de envio.'),

    ('configuracao.geral.view', 'configuracao', 'Configuração', 'geral', 'Geral', 'view', 1000, 'manage_general_settings', 'Visualizar configurações gerais.'),
    ('configuracao.geral.manage', 'configuracao', 'Configuração', 'geral', 'Geral', 'manage', 1001, 'manage_general_settings', 'Gerenciar configurações gerais.'),
    ('configuracao.notificacoes.view', 'configuracao', 'Configuração', 'notificacoes', 'Notificações', 'view', 1010, 'manage_general_settings', 'Visualizar notificações.'),
    ('configuracao.notificacoes.manage', 'configuracao', 'Configuração', 'notificacoes', 'Notificações', 'manage', 1011, 'manage_general_settings', 'Gerenciar notificações.'),
    ('configuracao.regionais.view', 'configuracao', 'Configuração', 'regionais', 'Regionais', 'view', 1020, 'view_regionais', 'Visualizar regionais.'),
    ('configuracao.regionais.manage', 'configuracao', 'Configuração', 'regionais', 'Regionais', 'manage', 1021, 'manage_regionais', 'Gerenciar regionais.'),
    ('configuracao.usuarios.view', 'configuracao', 'Configuração', 'usuarios', 'Usuários', 'view', 1030, 'manage_users', 'Visualizar usuários.'),
    ('configuracao.usuarios.manage', 'configuracao', 'Configuração', 'usuarios', 'Usuários', 'manage', 1031, 'manage_users', 'Gerenciar usuários.'),
    ('configuracao.cargos_permissoes.view', 'configuracao', 'Configuração', 'cargos_permissoes', 'Cargos e Permissões', 'view', 1040, 'manage_roles', 'Visualizar cargos e permissões.'),
    ('configuracao.cargos_permissoes.manage', 'configuracao', 'Configuração', 'cargos_permissoes', 'Cargos e Permissões', 'manage', 1041, 'manage_roles', 'Gerenciar cargos e permissões.'),
    ('configuracao.agentes.view', 'configuracao', 'Configuração', 'agentes', 'Agentes', 'view', 1050, 'view_agentes', 'Visualizar agentes.'),
    ('configuracao.agentes.manage', 'configuracao', 'Configuração', 'agentes', 'Agentes', 'manage', 1051, 'manage_agentes', 'Gerenciar agentes.'),
    ('configuracao.integracoes.view', 'configuracao', 'Configuração', 'integracoes', 'Integrações', 'view', 1060, 'view_integracoes', 'Visualizar integrações.'),
    ('configuracao.integracoes.manage', 'configuracao', 'Configuração', 'integracoes', 'Integrações', 'manage', 1061, 'manage_integracoes', 'Gerenciar integrações.'),
    ('configuracao.apis.view', 'configuracao', 'Configuração', 'apis', 'APIs', 'view', 1070, 'manage_api_status', 'Visualizar APIs.'),
    ('configuracao.apis.manage', 'configuracao', 'Configuração', 'apis', 'APIs', 'manage', 1071, 'manage_api_status', 'Gerenciar APIs.'),
    ('configuracao.hubsoft.view', 'configuracao', 'Configuração', 'hubsoft', 'Hubsoft', 'view', 1080, 'manage_integracoes', 'Visualizar Hubsoft.'),
    ('configuracao.hubsoft.manage', 'configuracao', 'Configuração', 'hubsoft', 'Hubsoft', 'manage', 1081, 'manage_integracoes', 'Gerenciar Hubsoft.'),
    ('configuracao.cvortex.view', 'configuracao', 'Configuração', 'cvortex', 'Cvortex', 'view', 1090, 'manage_integracoes', 'Visualizar Cvortex.'),
    ('configuracao.cvortex.manage', 'configuracao', 'Configuração', 'cvortex', 'Cvortex', 'manage', 1091, 'manage_integracoes', 'Gerenciar Cvortex.'),
    ('configuracao.banco_dados.view', 'configuracao', 'Configuração', 'banco_dados', 'Banco de Dados', 'view', 1100, 'manage_database_backups', 'Visualizar banco de dados.'),
    ('configuracao.banco_dados.manage', 'configuracao', 'Configuração', 'banco_dados', 'Banco de Dados', 'manage', 1101, 'manage_database_backups', 'Gerenciar banco de dados.'),
    ('configuracao.email.view', 'configuracao', 'Configuração', 'email', 'E-mail', 'view', 1110, 'manage_email', 'Visualizar e-mail.'),
    ('configuracao.email.manage', 'configuracao', 'Configuração', 'email', 'E-mail', 'manage', 1111, 'manage_email', 'Gerenciar e-mail.'),

    ('publico.painel_publico.view', 'publico', 'Público', 'painel_publico', 'Painel Público', 'view', 1200, null, 'Painéis públicos continuam sem exigir cargo, mas ficam catalogados para auditoria.')
)
insert into app_permissions (
  id,
  section_id,
  section_label,
  feature_id,
  feature_label,
  action,
  sort_order,
  legacy_permission,
  description,
  active,
  deprecated
)
select
  id,
  section_id,
  section_label,
  feature_id,
  feature_label,
  action,
  sort_order,
  legacy_permission,
  description,
  true,
  false
from permissions
on conflict (id) do update set
  section_id = excluded.section_id,
  section_label = excluded.section_label,
  feature_id = excluded.feature_id,
  feature_label = excluded.feature_label,
  action = excluded.action,
  sort_order = excluded.sort_order,
  legacy_permission = excluded.legacy_permission,
  description = excluded.description,
  active = excluded.active,
  deprecated = excluded.deprecated;

with permission_map(legacy_permission, new_permission) as (
  values
    ('view_dashboard', 'destaque.dashboard.view'),
    ('view_diario', 'destaque.diario.view'),
    ('view_mapa', 'destaque.mapa_os.view'),
    ('view_metas', 'destaque.metas.view'),
    ('manage_metas', 'destaque.metas.view'),
    ('manage_metas', 'destaque.metas.manage'),
    ('view_empresas_tecnicos', 'empresas.cadastro.view'),
    ('manage_empresas_tecnicos', 'empresas.cadastro.view'),
    ('manage_empresas_tecnicos', 'empresas.cadastro.manage'),
    ('view_agendamentos', 'cliente.agendamentos.view'),
    ('manage_agendamentos', 'cliente.agendamentos.view'),
    ('manage_agendamentos', 'cliente.agendamentos.manage'),
    ('view_entregas_tecnicos', 'tecnicos.entrega_tecnicos.view'),
    ('manage_entregas_tecnicos', 'tecnicos.entrega_tecnicos.view'),
    ('manage_entregas_tecnicos', 'tecnicos.entrega_tecnicos.manage'),
    ('view_estoque_integrado', 'tecnicos.bolsa_tecnico.view'),
    ('view_logistica', 'logistica.logistica.view'),
    ('manage_logistica', 'logistica.logistica.view'),
    ('manage_logistica', 'logistica.logistica.manage'),
    ('view_estoque_integrado', 'estoque.equipamentos.view'),
    ('manage_equipamentos', 'estoque.equipamentos.view'),
    ('manage_equipamentos', 'estoque.equipamentos.manage'),
    ('view_estoque_integrado', 'estoque.consulta.view'),
    ('view_acerto_estoque', 'estoque.acerto_estoque.view'),
    ('manage_acerto_estoque', 'estoque.acerto_estoque.view'),
    ('manage_acerto_estoque', 'estoque.acerto_estoque.manage'),
    ('view_documentos', 'administrativo.documentos.view'),
    ('view_documentos_tratativas', 'administrativo.documentos.view'),
    ('manage_documentos', 'administrativo.documentos.view'),
    ('manage_documentos', 'administrativo.documentos.manage'),
    ('view_insumos_administrativos', 'administrativo.insumos.view'),
    ('view_insumos_requisicoes', 'administrativo.insumos.view'),
    ('manage_insumos_administrativos', 'administrativo.insumos.view'),
    ('manage_insumos_administrativos', 'administrativo.insumos.manage'),
    ('view_imoveis_administrativos', 'administrativo.imoveis.view'),
    ('manage_imoveis_administrativos', 'administrativo.imoveis.view'),
    ('manage_imoveis_administrativos', 'administrativo.imoveis.manage'),
    ('view_documentos_relatorios', 'administrativo.relatorios.view'),
    ('manage_colaboradores', 'equipe.colaboradores.view'),
    ('manage_colaboradores', 'equipe.colaboradores.manage'),
    ('view_agenda', 'equipe.agenda.view'),
    ('manage_agenda', 'equipe.agenda.view'),
    ('manage_agenda', 'equipe.agenda.manage'),
    ('manage_feriados', 'equipe.feriados.view'),
    ('manage_feriados', 'equipe.feriados.manage'),
    ('request_ferias', 'equipe.ferias.view'),
    ('approve_ferias', 'equipe.ferias.view'),
    ('approve_ferias', 'equipe.ferias.manage'),
    ('view_mensageria', 'mensageria.enviados.view'),
    ('view_mensageria_relatorios', 'mensageria.relatorios.view'),
    ('view_confirmacao_agendamentos', 'mensageria.confirmacao_agendamentos.view'),
    ('manage_confirmacao_agendamentos', 'mensageria.confirmacao_agendamentos.view'),
    ('manage_confirmacao_agendamentos', 'mensageria.confirmacao_agendamentos.manage'),
    ('manage_mensageria', 'mensageria.fila.view'),
    ('manage_mensageria', 'mensageria.fila.manage'),
    ('manage_mensageria', 'mensageria.backlog.view'),
    ('manage_mensageria', 'mensageria.backlog.manage'),
    ('manage_mensageria', 'mensageria.callback.view'),
    ('manage_mensageria', 'mensageria.callback.manage'),
    ('manage_mensageria', 'mensageria.api.view'),
    ('manage_mensageria', 'mensageria.api.manage'),
    ('manage_mensageria', 'mensageria.email_config.view'),
    ('manage_mensageria', 'mensageria.email_config.manage'),
    ('manage_general_settings', 'configuracao.geral.view'),
    ('manage_general_settings', 'configuracao.geral.manage'),
    ('manage_general_settings', 'configuracao.notificacoes.view'),
    ('manage_general_settings', 'configuracao.notificacoes.manage'),
    ('view_regionais', 'configuracao.regionais.view'),
    ('manage_regionais', 'configuracao.regionais.view'),
    ('manage_regionais', 'configuracao.regionais.manage'),
    ('manage_users', 'configuracao.usuarios.view'),
    ('manage_users', 'configuracao.usuarios.manage'),
    ('manage_roles', 'configuracao.cargos_permissoes.view'),
    ('manage_roles', 'configuracao.cargos_permissoes.manage'),
    ('view_agentes', 'configuracao.agentes.view'),
    ('manage_agentes', 'configuracao.agentes.view'),
    ('manage_agentes', 'configuracao.agentes.manage'),
    ('view_integracoes', 'configuracao.integracoes.view'),
    ('manage_integracoes', 'configuracao.integracoes.view'),
    ('manage_integracoes', 'configuracao.integracoes.manage'),
    ('manage_api_status', 'configuracao.apis.view'),
    ('manage_api_status', 'configuracao.apis.manage'),
    ('manage_integracoes', 'configuracao.hubsoft.view'),
    ('manage_integracoes', 'configuracao.hubsoft.manage'),
    ('manage_integracoes', 'configuracao.cvortex.view'),
    ('manage_integracoes', 'configuracao.cvortex.manage'),
    ('manage_database_backups', 'configuracao.banco_dados.view'),
    ('manage_database_backups', 'configuracao.banco_dados.manage'),
    ('manage_email', 'configuracao.email.view'),
    ('manage_email', 'configuracao.email.manage')
)
insert into app_role_permissions (role_id, permission)
select distinct rp.role_id, pm.new_permission
from app_role_permissions rp
join permission_map pm on pm.legacy_permission = rp.permission
join app_permissions p on p.id = pm.new_permission
on conflict do nothing;
