import { criarRegional } from '../services/regionaisService';
import { criarAgente }   from '../services/agentesService';

const REGIONAIS = [
  {
    nome: 'CENTRAL MINEIRA',
    cidades: [
      { nome: 'IGARATINGA',           tipo: 'Comum' },
      { nome: 'PARÁ DE MINAS',        tipo: 'Comum' },
      { nome: 'QUARTEL GERAL',        tipo: 'Comum' },
      { nome: 'MARTINHO CAMPOS',      tipo: 'Agente Aut.' },
      { nome: 'BOM DESPACHO',         tipo: 'Agente Aut.' },
      { nome: 'CONCEIÇÃO DO PARÁ',    tipo: 'Comum' },
      { nome: 'SÃO JOSÉ DA VARGINHA', tipo: 'Comum' },
      { nome: 'CEDRO DO ABAETÉ',      tipo: 'Comum' },
      { nome: 'ONÇA DE PITANGUI',     tipo: 'Comum' },
      { nome: 'PITANGUI',             tipo: 'Comum' },
      { nome: 'LEANDRO FERREIRA',     tipo: 'Comum' },
      { nome: 'PAINEIRAS',            tipo: 'Comum' },
      { nome: 'ABAETÉ',               tipo: 'Comum' },
      { nome: 'SÃO GONÇALO DO PARÁ',  tipo: 'Comum' },
    ],
    supervisor: { nome: '', telefone: '', email: '' },
    lider:      { nome: '', telefone: '', email: '' },
    backoffice: { nome: '', telefone: '', email: '' },
  },
  {
    nome: 'SUL DE MINAS',
    cidades: [
      { nome: 'INGAÍ',                   tipo: 'Comum' },
      { nome: 'ITUMIRIM',                tipo: 'Comum' },
      { nome: 'NAZARENO',                tipo: 'Agente Aut.' },
      { nome: 'LUMINÁRIAS',              tipo: 'Comum' },
      { nome: 'NEPOMUCENO',              tipo: 'Comum' },
      { nome: 'CARMO DA CACHOEIRA',      tipo: 'Comum' },
      { nome: 'BOM SUCESSO',             tipo: 'Agente Aut.' },
      { nome: 'TRÊS CORAÇÕES',           tipo: 'Comum' },
      { nome: 'SÃO BENTO ABADE',         tipo: 'Comum' },
      { nome: 'IBITURUNA',               tipo: 'Agente Aut.' },
      { nome: 'SÃO TIAGO',               tipo: 'Agente Aut.' },
      { nome: 'LAVRAS',                  tipo: 'Comum' },
      { nome: 'SÃO THOMÉ DAS LETRAS',    tipo: 'Agente Aut.' },
      { nome: 'PERDÕES',                 tipo: 'Comum' },
      { nome: 'SANTO ANTÔNIO DO AMPARO', tipo: 'Comum' },
      { nome: 'ITUTINGA',                tipo: 'Agente Aut.' },
      { nome: 'CARRANCAS',               tipo: 'Comum' },
      { nome: 'IJACI',                   tipo: 'Comum' },
      { nome: 'RIBEIRÃO VERMELHO',       tipo: 'Comum' },
    ],
    supervisor: { nome: '', telefone: '', email: '' },
    lider:      { nome: '', telefone: '', email: '' },
    backoffice: { nome: '', telefone: '', email: '' },
  },
  {
    nome: 'OESTE DE MINAS',
    cidades: [
      { nome: 'PIUMHI',                 tipo: 'Comum' },
      { nome: 'PEDRA DO INDAIÁ',        tipo: 'Comum' },
      { nome: 'JAPARAÍBA',              tipo: 'Comum' },
      { nome: 'DIVINÓPOLIS',            tipo: 'Comum' },
      { nome: 'LAGOA DA PRATA',         tipo: 'Agente Aut.' },
      { nome: 'CLÁUDIO',                tipo: 'Comum' },
      { nome: 'CARMÓPOLIS DE MINAS',    tipo: 'Comum' },
      { nome: 'SANTO ANTÔNIO DO MONTE', tipo: 'Comum' },
      { nome: 'PERDIGÃO',               tipo: 'Agente Aut.' },
      { nome: 'CARMO DO CAJURU',        tipo: 'Comum' },
      { nome: 'IGUATAMA',               tipo: 'Comum' },
      { nome: 'ARAÚJOS',                tipo: 'Agente Aut.' },
      { nome: 'SÃO SEBASTIÃO DO OESTE', tipo: 'Comum' },
      { nome: 'CAMACHO',                tipo: 'Comum' },
      { nome: 'ITAPECERICA',            tipo: 'Comum' },
      { nome: 'DORESÓPOLIS',            tipo: 'Comum' },
    ],
    supervisor: { nome: '', telefone: '', email: '' },
    lider:      { nome: '', telefone: '', email: '' },
    backoffice: { nome: '', telefone: '', email: '' },
  },
  {
    nome: 'METROPOLITANA SUB2',
    cidades: [
      { nome: 'IBIRITÉ',            tipo: 'Comum' },
      { nome: 'PIEDADE DOS GERAIS', tipo: 'Comum' },
      { nome: 'MÁRIO CAMPOS',       tipo: 'Comum' },
      { nome: 'BONFIM',             tipo: 'Comum' },
      { nome: 'ITABIRITO',          tipo: 'Comum' },
      { nome: 'BRUMADINHO',         tipo: 'Comum' },
      { nome: 'BELO VALE',          tipo: 'Agente Aut.' },
      { nome: 'NOVA LIMA',          tipo: 'Comum' },
      { nome: 'SARZEDO',            tipo: 'Comum' },
      { nome: 'MOEDA',              tipo: 'Agente Aut.' },
      { nome: 'RIO MANSO',          tipo: 'Comum' },
    ],
    supervisor: { nome: '', telefone: '', email: '' },
    lider:      { nome: '', telefone: '', email: '' },
    backoffice: { nome: '', telefone: '', email: '' },
  },
  {
    nome: 'CENTRO OESTE',
    cidades: [
      { nome: 'ARCOS',                  tipo: 'Comum' },
      { nome: 'SÃO FRANCISCO DE PAULA', tipo: 'Comum' },
      { nome: 'AGUANIL',                tipo: 'Agente Aut.' },
      { nome: 'PAINS',                  tipo: 'Comum' },
      { nome: 'CRISTAIS',               tipo: 'Agente Aut.' },
      { nome: 'SANTANA DO JACARÉ',      tipo: 'Agente Aut.' },
      { nome: 'CAMPO BELO',             tipo: 'Comum' },
      { nome: 'CÓRREGO FUNDO',          tipo: 'Agente Aut.' },
      { nome: 'CANDEIAS',               tipo: 'Comum' },
      { nome: 'FORMIGA',                tipo: 'Agente Aut.' },
      { nome: 'CANA VERDE',             tipo: 'Agente Aut.' },
      { nome: 'OLIVEIRA',               tipo: 'Comum' },
      { nome: 'CARMO DA MATA',          tipo: 'Comum' },
    ],
    supervisor: { nome: '', telefone: '', email: '' },
    lider:      { nome: '', telefone: '', email: '' },
    backoffice: { nome: '', telefone: '', email: '' },
  },
  {
    nome: 'METROPOLITANA SUB3',
    cidades: [
      { nome: 'JEQUITIBÁ',          tipo: 'Comum' },
      { nome: 'JABOTICATUBAS',       tipo: 'Comum' },
      { nome: 'CORDISBURGO',         tipo: 'Comum' },
      { nome: 'SETE LAGOAS',         tipo: 'Comum' },
      { nome: 'SANTANA DE PIRAPAMA', tipo: 'Comum' },
      { nome: 'MATOZINHOS',          tipo: 'Comum' },
      { nome: 'CACHOEIRA DA PRATA',  tipo: 'Comum' },
      { nome: 'ARAÇAI',              tipo: 'Comum' },
      { nome: 'PRUDENTE DE MORAIS',  tipo: 'Comum' },
      { nome: 'FUNILÂNDIA',          tipo: 'Comum' },
      { nome: 'CAPIM BRANCO',        tipo: 'Comum' },
      { nome: 'BALDIM',              tipo: 'Comum' },
      { nome: 'FORTUNA DE MINAS',    tipo: 'Comum' },
      { nome: 'INHAÚMA',             tipo: 'Comum' },
    ],
    supervisor: { nome: '', telefone: '', email: '' },
    lider:      { nome: '', telefone: '', email: '' },
    backoffice: { nome: '', telefone: '', email: '' },
  },
  {
    nome: 'METROPOLITANA SUB1',
    cidades: [
      { nome: 'BELO HORIZONTE',       tipo: 'Comum' },
      { nome: 'CRUCILANDIA',          tipo: 'Comum' },
      { nome: 'IGARAPÉ',              tipo: 'Comum' },
      { nome: 'FLORESTAL',            tipo: 'Comum' },
      { nome: 'SÃO JOAQUIM DE BICAS', tipo: 'Comum' },
      { nome: 'ITAGUARA',             tipo: 'Comum' },
      { nome: 'MATEUS LEME',          tipo: 'Comum' },
      { nome: 'PIRACEMA',             tipo: 'Comum' },
      { nome: 'BETIM',                tipo: 'Comum' },
      { nome: 'JUATUBA',              tipo: 'Comum' },
      { nome: 'ESMERALDAS',           tipo: 'Comum' },
      { nome: 'CONTAGEM',             tipo: 'Comum' },
    ],
    supervisor: { nome: '', telefone: '', email: '' },
    lider:      { nome: '', telefone: '', email: '' },
    backoffice: { nome: '', telefone: '', email: '' },
  },
];

const AGENTES_SEED = [
  { cidade: 'MARTINHO CAMPOS',      regional_nome: 'CENTRAL MINEIRA',    responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'BOM DESPACHO',         regional_nome: 'CENTRAL MINEIRA',    responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'NAZARENO',             regional_nome: 'SUL DE MINAS',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'BOM SUCESSO',          regional_nome: 'SUL DE MINAS',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'IBITURUNA',            regional_nome: 'SUL DE MINAS',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'SÃO TIAGO',            regional_nome: 'SUL DE MINAS',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'SÃO THOMÉ DAS LETRAS', regional_nome: 'SUL DE MINAS',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'ITUTINGA',             regional_nome: 'SUL DE MINAS',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'LAGOA DA PRATA',       regional_nome: 'OESTE DE MINAS',     responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'PERDIGÃO',             regional_nome: 'OESTE DE MINAS',     responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'ARAÚJOS',              regional_nome: 'OESTE DE MINAS',     responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'BELO VALE',            regional_nome: 'METROPOLITANA SUB2', responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'MOEDA',                regional_nome: 'METROPOLITANA SUB2', responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'AGUANIL',              regional_nome: 'CENTRO OESTE',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'CRISTAIS',             regional_nome: 'CENTRO OESTE',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'SANTANA DO JACARÉ',    regional_nome: 'CENTRO OESTE',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'CÓRREGO FUNDO',        regional_nome: 'CENTRO OESTE',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'FORMIGA',              regional_nome: 'CENTRO OESTE',       responsavel: { nome: '', telefone: '', email: '' } },
  { cidade: 'CANA VERDE',           regional_nome: 'CENTRO OESTE',       responsavel: { nome: '', telefone: '', email: '' } },
];

export const seedAll = async () => {
  console.log('Iniciando seed de regionais...');
  for (const regional of REGIONAIS) {
    await criarRegional(regional);
    console.log(`✅ Regional: ${regional.nome} (${regional.cidades.length} cidades)`);
  }
  console.log('\nIniciando seed de agentes autorizados...');
  for (const agente of AGENTES_SEED) {
    await criarAgente(agente);
    console.log(`⭐ Agente: ${agente.cidade} — ${agente.regional_nome}`);
  }
  console.log('\n🎉 Seed concluído! 7 regionais, 99 cidades, 19 agentes autorizados.');
};
