const DEFAULT_FINANCIAL_ACCOUNT_PLAN = [
	{
		classification: "1.01",
		code: "11",
		reducedCode: "11",
		name: "RECEITAS",
		planType: "S",
		level: 2,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.01.01",
		code: "111",
		reducedCode: "111",
		name: "RECEITA DE TELECOMUNICAÇÕES",
		planType: "S",
		level: 3,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "11",
	},
	{
		classification: "1.01.01.01",
		code: "11111",
		reducedCode: "11.111",
		name: "RECEITAS DE TELECOMUNICACOES",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "111",
	},
	{
		classification: "1.01.01.01.01",
		code: "1111",
		reducedCode: "1.111",
		name: "Receita de Serviço de Comunicação Multimídia - SCM",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11111",
	},
	{
		classification: "1.01.01.01.02",
		code: "1112",
		reducedCode: "1.112",
		name: "Receita de Serviço de Acesso Condicionado - SeAC",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11111",
	},
	{
		classification: "1.01.01.01.03",
		code: "1113",
		reducedCode: "1.113",
		name: "Receita de Serviço de Instalação e Manutenção",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11111",
	},
	{
		classification: "1.01.01.01.04",
		code: "1114",
		reducedCode: "1.114",
		name: "Receita de Serviço de Telefonia Fixa - STFC",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11111",
	},
	{
		classification: "1.01.01.01.05",
		code: "1115",
		reducedCode: "1.115",
		name: "Receita de Serviço de Telefonia Móvel - SMP",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11111",
	},
	{
		classification: "1.01.01.01.06",
		code: "1116",
		reducedCode: "1.116",
		name: "Receita de Outros Serviços de Telecomunicação",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11111",
	},
	{
		classification: "1.01.02",
		code: "112",
		reducedCode: "112",
		name: "RECEITA DE SERVICOS DE VALOR ADICIONADO",
		planType: "S",
		level: 3,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "11",
	},
	{
		classification: "1.01.02.01",
		code: "11211",
		reducedCode: "11.211",
		name: "RECEITA DE SERVICOS DE VALOR ADICIONADO",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "112",
	},
	{
		classification: "1.01.02.01.01",
		code: "1121",
		reducedCode: "1.121",
		name: "Receita de Serviços Digitais",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11211",
	},
	{
		classification: "1.01.02.01.02",
		code: "1122",
		reducedCode: "1.122",
		name: "Receita de Teleatendimento",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11211",
	},
	{
		classification: "1.01.02.01.03",
		code: "1136",
		reducedCode: "1.136",
		name: "Receita de Serviços de Valor Adicionado - Crédito de Terceiras operações",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11211",
	},
	{
		classification: "1.01.03",
		code: "113",
		reducedCode: "113",
		name: "OUTRAS RECEITAS",
		planType: "S",
		level: 3,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "11",
	},
	{
		classification: "1.01.03.01",
		code: "1131",
		reducedCode: "1.131",
		name: "RECEITAS FINANCEIRAS",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "113",
	},
	{
		classification: "1.01.03.01.01",
		code: "11311",
		reducedCode: "11.311",
		name: "Juros Recebidos s/duplicatas",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.02",
		code: "11312",
		reducedCode: "11.312",
		name: "Descontos Obtidos",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.03",
		code: "11313",
		reducedCode: "11.313",
		name: "Var. Monetária Ativa s/atualizações",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.04",
		code: "11314",
		reducedCode: "11.314",
		name: "Juros Ativos",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.05",
		code: "11315",
		reducedCode: "11.315",
		name: "Variação Monetária Ativa",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.06",
		code: "11316",
		reducedCode: "11.316",
		name: "Receitas Aplicações Financeiras",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.07",
		code: "11317",
		reducedCode: "11.317",
		name: "Bonificação de Dividendos",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.08",
		code: "11318",
		reducedCode: "11.318",
		name: "Bonificações",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.09",
		code: "11319",
		reducedCode: "11.319",
		name: "Amostras grátis",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.10",
		code: "11320",
		reducedCode: "11.320",
		name: "Atualização de Créditos Federais",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.11",
		code: "11321",
		reducedCode: "11.321",
		name: "Multa s/ Rescisão de Contrato de Prest. de Serviço",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.12",
		code: "11322",
		reducedCode: "11.322",
		name: "Juros Recebidos s/duplicatas",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.01.13",
		code: "1132",
		reducedCode: "1.132",
		name: "Receitas de Cobrança",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1131",
	},
	{
		classification: "1.01.03.03",
		code: "1133",
		reducedCode: "1.133",
		name: "RECEITA DE VENDAS DE EQUIPAMENTO",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "113",
	},
	{
		classification: "1.01.03.03.01",
		code: "11331",
		reducedCode: "11.331",
		name: "Receita Alienação de Bens Ativo Permanen",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1133",
	},
	{
		classification: "1.01.03.03.02",
		code: "11332",
		reducedCode: "11.332",
		name: "(-)Vr.Contábil Bens e Direitos Alienados",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1133",
	},
	{
		classification: "1.01.03.03.03",
		code: "11333",
		reducedCode: "11.333",
		name: "Venda de Sucata",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1133",
	},
	{
		classification: "1.01.03.03.04",
		code: "1134",
		reducedCode: "1.134",
		name: "Receita Indenização de Equipamentos",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1133",
	},
	{
		classification: "1.01.03.08",
		code: "1138",
		reducedCode: "1.138",
		name: "OUTRAS RECEITAS OPERACIONAIS",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "113",
	},
	{
		classification: "1.01.03.08.01",
		code: "11381",
		reducedCode: "11.381",
		name: "Atualiz. Monetária",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.02",
		code: "11382",
		reducedCode: "11.382",
		name: "Locação",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.03",
		code: "11383",
		reducedCode: "11.383",
		name: "Taxas",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.04",
		code: "11384",
		reducedCode: "11.384",
		name: "Juros",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.05",
		code: "11385",
		reducedCode: "11.385",
		name: "Ingressos p/Congresso",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.06",
		code: "11386",
		reducedCode: "11.386",
		name: "Direitos Autorais",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.07",
		code: "11387",
		reducedCode: "11.387",
		name: "Royalties",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.08",
		code: "11388",
		reducedCode: "11.388",
		name: "Lucros Recebidos Partic. Em Outras Emp.",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.09",
		code: "11389",
		reducedCode: "11.389",
		name: "Receita com Equivalência Patrimonial",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.10",
		code: "11390",
		reducedCode: "11.390",
		name: "Receita a Incorrer",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.11",
		code: "11391",
		reducedCode: "11.391",
		name: "Receita de Venda a Faturar",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.12",
		code: "11392",
		reducedCode: "11.392",
		name: "Alugueis",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.13",
		code: "11393",
		reducedCode: "11.393",
		name: "Desagio Debitos Bancarios",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.14",
		code: "11394",
		reducedCode: "11.394",
		name: "Outras Receitas com Programa de Pontos",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.15",
		code: "11395",
		reducedCode: "11.395",
		name: "Receita com Reversão de Provisão para Crédito de Liquidação",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.16",
		code: "1135",
		reducedCode: "1.135",
		name: "Recuperação de Despesas",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.17",
		code: "1137",
		reducedCode: "1.137",
		name: "Receita de Recebimento de Contrato Mútuo",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.03.08.18",
		code: "11396",
		reducedCode: "11.396",
		name: "Patrocínios",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1138",
	},
	{
		classification: "1.01.04",
		code: "110",
		reducedCode: "110",
		name: "RECEITA DE ALUGUEL",
		planType: "S",
		level: 3,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "11",
	},
	{
		classification: "1.01.04.01",
		code: "1141",
		reducedCode: "1.141",
		name: "RECEITAS DE ALUGUEL",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "110",
	},
	{
		classification: "1.01.04.01.01",
		code: "13013",
		reducedCode: "13.013",
		name: "Receita de Aluguel de Equipamentos",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1141",
	},
	{
		classification: "1.01.04.01.02",
		code: "13014",
		reducedCode: "13.014",
		name: "Receita de Aluguel de Infraestrutura",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1141",
	},
	{
		classification: "1.01.04.01.03",
		code: "13015",
		reducedCode: "13.015",
		name: "Receita de Aluguel de Software",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1141",
	},
	{
		classification: "1.01.04.01.04",
		code: "13016",
		reducedCode: "13.016",
		name: "Outras Receitas de Aluguel",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "1141",
	},
	{
		classification: "1.01.05",
		code: "115",
		reducedCode: "115",
		name: "(-)VENDAS CANCELADAS E DESCONT. INCONDIC.",
		planType: "S",
		level: 3,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "11",
	},
	{
		classification: "1.01.05.01",
		code: "11511",
		reducedCode: "11.511",
		name: "(-)VENDAS CANCELADAS E DESCONT. INCONDIC.",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "115",
	},
	{
		classification: "1.01.05.01.01",
		code: "1151",
		reducedCode: "1.151",
		name: "(-) Vendas Canceladas",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11511",
	},
	{
		classification: "1.01.05.01.02",
		code: "1152",
		reducedCode: "1.152",
		name: "(-) Serviços Cancelados",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "11511",
	},
	{
		classification: "1.02",
		code: "12",
		reducedCode: "12",
		name: "CUSTOS",
		planType: "S",
		level: 2,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.02.01",
		code: "121",
		reducedCode: "121",
		name: "CUSTO: CONSUMO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.01.01",
		code: "12111",
		reducedCode: "12.111",
		name: "CUSTO: CONSUMO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "121",
	},
	{
		classification: "1.02.01.01.01",
		code: "1211",
		reducedCode: "1.211",
		name: "Energia Elétrica (Torres, POPs, Cessão de Energia)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12111",
	},
	{
		classification: "1.02.01.02",
		code: "1212",
		reducedCode: "1.212",
		name: "FERRAMENTAS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "121",
	},
	{
		classification: "1.02.01.02.01",
		code: "12121",
		reducedCode: "12.121",
		name: "Bens de Valores Reduzidos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1212",
	},
	{
		classification: "1.02.01.02.02",
		code: "12122",
		reducedCode: "12.122",
		name: "Ferramentas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1212",
	},
	{
		classification: "1.02.01.02.03",
		code: "1213",
		reducedCode: "1.213",
		name: "INATIVO - Material de Consumo Operacional",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1212",
	},
	{
		classification: "1.02.02",
		code: "122",
		reducedCode: "122",
		name: "CUSTO: INSTALAÇÃO/MANUTENÇÃO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.02.01",
		code: "12211",
		reducedCode: "12.211",
		name: "CUSTO: INSTALAÇÃO/MANUTENÇÃO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "122",
	},
	{
		classification: "1.02.02.01.01",
		code: "1221",
		reducedCode: "1.221",
		name: "Cabo Drop",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12211",
	},
	{
		classification: "1.02.02.01.02",
		code: "1223",
		reducedCode: "1.223",
		name: "Roteador / ONU / Modem",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12211",
	},
	{
		classification: "1.02.02.01.03",
		code: "1224",
		reducedCode: "1.224",
		name: "Serviços de Instalação (técnicos)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12211",
	},
	{
		classification: "1.02.02.01.04",
		code: "1225",
		reducedCode: "1.225",
		name: "Serviços de Manutenção (técnicos)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12211",
	},
	{
		classification: "1.02.02.01.05",
		code: "1226",
		reducedCode: "1.226",
		name: "Materiais de Instalação (metais, conectores, etc)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12211",
	},
	{
		classification: "1.02.02.02",
		code: "12221",
		reducedCode: "12.221",
		name: "IMPOSTOS SOBRE COMPRA",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "122",
	},
	{
		classification: "1.02.02.02.01",
		code: "12222",
		reducedCode: "12.222",
		name: "(-) Devolução de Insumos Aplicados na Prestação de Serviço",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12221",
	},
	{
		classification: "1.02.02.02.02",
		code: "12223",
		reducedCode: "12.223",
		name: "(-) ICMS Sobre Outras Entradas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12221",
	},
	{
		classification: "1.02.02.02.03",
		code: "12224",
		reducedCode: "12.224",
		name: "ICMS ST",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12221",
	},
	{
		classification: "1.02.02.02.04",
		code: "12225",
		reducedCode: "12.225",
		name: "Fretes e Carretos s/ Insumos Aplicados no Serviço",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12221",
	},
	{
		classification: "1.02.02.02.05",
		code: "12226",
		reducedCode: "12.226",
		name: "ICMS ST s/ Fretes e Carretos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12221",
	},
	{
		classification: "1.02.02.02.06",
		code: "12227",
		reducedCode: "12.227",
		name: "ICMS Diferença de Alíquota s/ Fretes e Carretos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12221",
	},
	{
		classification: "1.02.02.08",
		code: "1222",
		reducedCode: "1.222",
		name: "INATIVO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "122",
	},
	{
		classification: "1.02.03",
		code: "123",
		reducedCode: "123",
		name: "CUSTO: INTERCONEXÃO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.03.01",
		code: "12311",
		reducedCode: "12.311",
		name: "CUSTO: INTERCONEXÃO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "123",
	},
	{
		classification: "1.02.03.01.01",
		code: "1231",
		reducedCode: "1.231",
		name: "Aluguel de Rack / Cross Conexões",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12311",
	},
	{
		classification: "1.02.03.01.02",
		code: "1232",
		reducedCode: "1.232",
		name: "Link",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12311",
	},
	{
		classification: "1.02.03.01.03",
		code: "1233",
		reducedCode: "1.233",
		name: "Link Last Mile",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12311",
	},
	{
		classification: "1.02.04",
		code: "124",
		reducedCode: "124",
		name: "CUSTO: LOGÍSTICA",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.04.01",
		code: "1241",
		reducedCode: "1.241",
		name: "ALUGUEL DE VEÍCULOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "124",
	},
	{
		classification: "1.02.04.01.01",
		code: "12411",
		reducedCode: "12.411",
		name: "Aluguel de Veículos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1241",
	},
	{
		classification: "1.02.04.01.02",
		code: "12412",
		reducedCode: "12.412",
		name: "INATIVO - Aluguel de Veículos C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1241",
	},
	{
		classification: "1.02.04.02",
		code: "1242",
		reducedCode: "1.242",
		name: "COMBUSTÍVEIS E LUBRIFICANTES",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "124",
	},
	{
		classification: "1.02.04.02.01",
		code: "12421",
		reducedCode: "12.421",
		name: "Combustíveis - Veículos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1242",
	},
	{
		classification: "1.02.04.02.02",
		code: "12422",
		reducedCode: "12.422",
		name: "INATIVO - Combustíveis e Lubrificantes - Veículos C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1242",
	},
	{
		classification: "1.02.04.02.03",
		code: "12423",
		reducedCode: "12.423",
		name: "INATIVO - Combustíveis e Lubrificantes - Máquinas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1242",
	},
	{
		classification: "1.02.04.02.04",
		code: "12424",
		reducedCode: "12.424",
		name: "INATIVO - Combustíveis e Lubrificantes - Máquinas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1242",
	},
	{
		classification: "1.02.04.04",
		code: "1244",
		reducedCode: "1.244",
		name: "VIAGENS E ESTADIAS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "124",
	},
	{
		classification: "1.02.04.04.01",
		code: "12441",
		reducedCode: "12.441",
		name: "Despesas de Viagens e Estadias",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1244",
	},
	{
		classification: "1.02.04.04.02",
		code: "1243",
		reducedCode: "1.243",
		name: "Estacionamento e Pedágios",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1244",
	},
	{
		classification: "1.02.04.04.99",
		code: "12442",
		reducedCode: "12.442",
		name: "INATIVO - Despesas de Viagens e Estadias C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1244",
	},
	{
		classification: "1.02.05",
		code: "125",
		reducedCode: "125",
		name: "CUSTO: PRODUTO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.05.01",
		code: "12511",
		reducedCode: "12.511",
		name: "CUSTO: PRODUTO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "125",
	},
	{
		classification: "1.02.05.01.01",
		code: "1251",
		reducedCode: "1.251",
		name: "Serviços Digitais",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12511",
	},
	{
		classification: "1.02.06",
		code: "126",
		reducedCode: "126",
		name: "CUSTO: TRANSMISSÃO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.06.01",
		code: "12611",
		reducedCode: "12.611",
		name: "CUSTO: TRANSMISSÃO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "126",
	},
	{
		classification: "1.02.06.01.01",
		code: "1261",
		reducedCode: "1.261",
		name: "Aluguel Postes",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12611",
	},
	{
		classification: "1.02.06.01.02",
		code: "1262",
		reducedCode: "1.262",
		name: "Aluguel Torres",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12611",
	},
	{
		classification: "1.02.06.01.03",
		code: "1263",
		reducedCode: "1.263",
		name: "Aluguel de Infraestrutura - Dutos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12611",
	},
	{
		classification: "1.02.07",
		code: "127",
		reducedCode: "127",
		name: "CUSTO: REDE",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.07.01",
		code: "12711",
		reducedCode: "12.711",
		name: "CUSTO: REDE",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "127",
	},
	{
		classification: "1.02.07.01.01",
		code: "1273",
		reducedCode: "1.273",
		name: "Equipamentos POP (Switches, OTDR, Baterias)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12711",
	},
	{
		classification: "1.02.07.01.02",
		code: "1274",
		reducedCode: "1.274",
		name: "Geradores Energia",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12711",
	},
	{
		classification: "1.02.07.01.03",
		code: "1276",
		reducedCode: "1.276",
		name: "Rede de Backbone e Rede Ramal",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12711",
	},
	{
		classification: "1.02.07.01.97",
		code: "1271",
		reducedCode: "1.271",
		name: "INATIVO - Antenas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "inativo",
		parentCode: "12711",
	},
	{
		classification: "1.02.07.01.98",
		code: "1272",
		reducedCode: "1.272",
		name: "INATIVO - Concentradores (Roteadores e OLTs)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "inativo",
		parentCode: "12711",
	},
	{
		classification: "1.02.07.01.99",
		code: "1275",
		reducedCode: "1.275",
		name: "INATIVO - Máquinas e Equipamentos Operacionais",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "inativo",
		parentCode: "12711",
	},
	{
		classification: "1.02.09",
		code: "129",
		reducedCode: "129",
		name: "CUSTO: AQUISIÇÕES",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "12",
	},
	{
		classification: "1.02.09.01",
		code: "12911",
		reducedCode: "12.911",
		name: "CUSTO: AQUISIÇÕES",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "129",
	},
	{
		classification: "1.02.09.01.01",
		code: "1291",
		reducedCode: "1.291",
		name: "Provedores",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12911",
	},
	{
		classification: "1.02.09.01.02",
		code: "1292",
		reducedCode: "1.292",
		name: "Veículos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "12911",
	},
	{
		classification: "1.02.09.01.03",
		code: "1293",
		reducedCode: "1.293",
		name: "INATIVO - Veículos Grande Porte",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "12911",
	},
	{
		classification: "1.03",
		code: "13",
		reducedCode: "13",
		name: "DESPESAS",
		planType: "S",
		level: 2,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.03.01",
		code: "131",
		reducedCode: "131",
		name: "DESPESA: ADMINISTRATIVO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.01.01",
		code: "1311",
		reducedCode: "1.311",
		name: "CONSERVAÇÃO E LIMPEZA",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "131",
	},
	{
		classification: "1.03.01.01.01",
		code: "13111",
		reducedCode: "13.111",
		name: "Serviços de Conservação e Limpeza",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1311",
	},
	{
		classification: "1.03.01.01.02",
		code: "1312",
		reducedCode: "1.312",
		name: "Copa e Cozinha",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1311",
	},
	{
		classification: "1.03.01.03",
		code: "1313",
		reducedCode: "1.313",
		name: "DESPESAS GERAIS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "131",
	},
	{
		classification: "1.03.01.03.01",
		code: "13131",
		reducedCode: "13.131",
		name: "Xérox e Autenticação",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.02",
		code: "13132",
		reducedCode: "13.132",
		name: "Material Escrit Impressos e Mat de Exped",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.03",
		code: "13133",
		reducedCode: "13.133",
		name: "Assinaturas de Jornais/Revistas/Editais",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.04",
		code: "13134",
		reducedCode: "13.134",
		name: "Fretes e Carretos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.05",
		code: "13135",
		reducedCode: "13.135",
		name: "Material de Consumo",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.06",
		code: "13136",
		reducedCode: "13.136",
		name: "Despesas c/ cartório, autenticação e xerox",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.07",
		code: "13137",
		reducedCode: "13.137",
		name: "Correios",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.08",
		code: "13138",
		reducedCode: "13.138",
		name: "Locações Diversas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.09",
		code: "13139",
		reducedCode: "13.139",
		name: "INATIVO - Despesas c/Internet",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.10",
		code: "13140",
		reducedCode: "13.140",
		name: "Direitos Autorais",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.11",
		code: "1314",
		reducedCode: "1.314",
		name: "Lanches e Refeições",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.12",
		code: "13141",
		reducedCode: "13.141",
		name: "INATIVO - Lanches e Refeições D",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.13",
		code: "13142",
		reducedCode: "13.142",
		name: "INATIVO - Lanches e Refeições C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.01.03.14",
		code: "1315",
		reducedCode: "1.315",
		name: "INATIVO - TAI - Implantação",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1313",
	},
	{
		classification: "1.03.02",
		code: "132",
		reducedCode: "132",
		name: "DESPESA: COMERCIAL",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.02.01",
		code: "13211",
		reducedCode: "13.211",
		name: "DESPESAS: COMERCIAL",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "132",
	},
	{
		classification: "1.03.02.01.01",
		code: "1321",
		reducedCode: "1.321",
		name: "Ações de venda",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.02.01.02",
		code: "1322",
		reducedCode: "1.322",
		name: "Comissões PF",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.02.01.03",
		code: "1323",
		reducedCode: "1.323",
		name: "Comissões PJ",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.02.01.04",
		code: "1324",
		reducedCode: "1.324",
		name: "Marketing de relacionamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.02.01.05",
		code: "1325",
		reducedCode: "1.325",
		name: "Marketing Institucional",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.02.01.06",
		code: "1326",
		reducedCode: "1.326",
		name: "Pesquisa e Análise de Mercado",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.02.01.07",
		code: "1327",
		reducedCode: "1.327",
		name: "Propaganda",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.02.01.08",
		code: "1328",
		reducedCode: "1.328",
		name: "Feiras, Congressos e Exposições",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13211",
	},
	{
		classification: "1.03.03",
		code: "133",
		reducedCode: "133",
		name: "DESPESA: CONSERVAÇÃO E REPARO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.03.01",
		code: "1331",
		reducedCode: "1.331",
		name: "MANUTENÇÃO CORRETIVA DE MÁQUINAS E EQUIPAMENTOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "133",
	},
	{
		classification: "1.03.03.01.01",
		code: "13311",
		reducedCode: "13.311",
		name: "Manutenção de Máquinas e Equipamentos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1331",
	},
	{
		classification: "1.03.03.01.02",
		code: "13312",
		reducedCode: "13.312",
		name: "INATIVO - Reparacao de Maquinas e Equipamentos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1331",
	},
	{
		classification: "1.03.03.02",
		code: "1335",
		reducedCode: "1.335",
		name: "MANUTENCAO DE IMOVEIS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "133",
	},
	{
		classification: "1.03.03.02.01",
		code: "1332",
		reducedCode: "1.332",
		name: "Manutenção de Imóveis",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1335",
	},
	{
		classification: "1.03.03.02.02",
		code: "1334",
		reducedCode: "1.334",
		name: "INATIVO - Reforma Lojas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1335",
	},
	{
		classification: "1.03.03.02.03",
		code: "1333",
		reducedCode: "1.333",
		name: "INATIVO - Manutenção Preventiva de Imóveis",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "inativo",
		parentCode: "1335",
	},
	{
		classification: "1.03.04",
		code: "134",
		reducedCode: "134",
		name: "DESPESA: FINANCEIRA",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.04.01",
		code: "1348",
		reducedCode: "1.348",
		name: "DESPESAS: FINANCEIRA",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "134",
	},
	{
		classification: "1.03.04.01.01",
		code: "1341",
		reducedCode: "1.341",
		name: "Consórcio",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1348",
	},
	{
		classification: "1.03.04.01.02",
		code: "1342",
		reducedCode: "1.342",
		name: "Doações",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1348",
	},
	{
		classification: "1.03.04.01.03",
		code: "1343",
		reducedCode: "1.343",
		name: "Empréstimos bancários",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1348",
	},
	{
		classification: "1.03.04.01.04",
		code: "1344",
		reducedCode: "1.344",
		name: "Empréstimos c/ partes relacionadas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1348",
	},
	{
		classification: "1.03.04.01.05",
		code: "1345",
		reducedCode: "1.345",
		name: "Quebras e pequenos ajustes",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1348",
	},
	{
		classification: "1.03.04.01.06",
		code: "1347",
		reducedCode: "1.347",
		name: "Juros sobre Empréstimos Variável",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1348",
	},
	{
		classification: "1.03.04.01.07",
		code: "13021",
		reducedCode: "13.021",
		name: "Aplicações Financeiras",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1348",
	},
	{
		classification: "1.03.04.02",
		code: "1346",
		reducedCode: "1.346",
		name: "SEGUROS PATRIMONIAL",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "134",
	},
	{
		classification: "1.03.04.02.01",
		code: "13461",
		reducedCode: "13.461",
		name: "Seguros",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1346",
	},
	{
		classification: "1.03.04.02.02",
		code: "13462",
		reducedCode: "13.462",
		name: "INATIVO - Seguros C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1346",
	},
	{
		classification: "1.03.05",
		code: "135",
		reducedCode: "135",
		name: "DESPESA: JUROS E IOF",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.05.01",
		code: "1354",
		reducedCode: "1.354",
		name: "DESPESA: JUROS E IOF",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "135",
	},
	{
		classification: "1.03.05.01.02",
		code: "1352",
		reducedCode: "1.352",
		name: "Juros s/ duplicatas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1354",
	},
	{
		classification: "1.03.05.01.03",
		code: "1351",
		reducedCode: "1.351",
		name: "IOF",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1354",
	},
	{
		classification: "1.03.05.01.04",
		code: "1353",
		reducedCode: "1.353",
		name: "Juros s/ impostos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1354",
	},
	{
		classification: "1.03.05.01.05",
		code: "13022",
		reducedCode: "13.022",
		name: "IRRF sobre Aplicações",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1354",
	},
	{
		classification: "1.03.06",
		code: "136",
		reducedCode: "136",
		name: "DESPESA: OCUPAÇÃO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.06.01",
		code: "1365",
		reducedCode: "1.365",
		name: "DESPESA: OCUPAÇÃO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "136",
	},
	{
		classification: "1.03.06.01.01",
		code: "1361",
		reducedCode: "1.361",
		name: "Aluguel",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1365",
	},
	{
		classification: "1.03.06.01.02",
		code: "1362",
		reducedCode: "1.362",
		name: "Condomínio",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1365",
	},
	{
		classification: "1.03.06.01.03",
		code: "1363",
		reducedCode: "1.363",
		name: "IPTU",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1365",
	},
	{
		classification: "1.03.06.01.04",
		code: "1364",
		reducedCode: "1.364",
		name: "Móveis e Utensílios",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1365",
	},
	{
		classification: "1.03.06.01.05",
		code: "13017",
		reducedCode: "13.017",
		name: "Segurança e Monitoramento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1365",
	},
	{
		classification: "1.03.07",
		code: "137",
		reducedCode: "137",
		name: "DESPESA: PESSOAL",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.07.01",
		code: "1371",
		reducedCode: "1.371",
		name: "BENEFÍCIOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "137",
	},
	{
		classification: "1.03.07.01.01",
		code: "13711",
		reducedCode: "13.711",
		name: "Vale transporte",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.02",
		code: "13712",
		reducedCode: "13.712",
		name: "Medicamentos e Assistência Médica",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.03",
		code: "13713",
		reducedCode: "13.713",
		name: "Programa de Alimentação do Trabalhador",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.04",
		code: "13714",
		reducedCode: "13.714",
		name: "Ajuda de Custo",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.05",
		code: "13715",
		reducedCode: "13.715",
		name: "Seguros de Vida",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.06",
		code: "13716",
		reducedCode: "13.716",
		name: "Programas de Bem-estar",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.07",
		code: "13717",
		reducedCode: "13.717",
		name: "INATIVO - Medicamentos e Assistência Médica C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.08",
		code: "13718",
		reducedCode: "13.718",
		name: "INATIVO - Programa de Alimentação do Trabalhador C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.09",
		code: "13719",
		reducedCode: "13.719",
		name: "Convênio Farmacia",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.10",
		code: "13720",
		reducedCode: "13.720",
		name: "INATIVO - Vale Combustível C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.11",
		code: "13721",
		reducedCode: "13.721",
		name: "INATIVO - Seguros de Vida C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.12",
		code: "1372",
		reducedCode: "1.372",
		name: "Capacitação e Desenvolvimento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.01.13",
		code: "1375",
		reducedCode: "1.375",
		name: "Eventos Comemorativos e Homenagens",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1371",
	},
	{
		classification: "1.03.07.03",
		code: "1373",
		reducedCode: "1.373",
		name: "COMISSÕES / PRÊMIO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "137",
	},
	{
		classification: "1.03.07.03.01",
		code: "13731",
		reducedCode: "13.731",
		name: "Premios e Bonificações",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1373",
	},
	{
		classification: "1.03.07.03.02",
		code: "13732",
		reducedCode: "13.732",
		name: "INATIVO - Premios e Bonificações C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1373",
	},
	{
		classification: "1.03.07.04",
		code: "37143",
		reducedCode: "37.143",
		name: "PESSOAL",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "137",
	},
	{
		classification: "1.03.07.04.01",
		code: "1379",
		reducedCode: "1.379",
		name: "Salários e Ordenados",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.02",
		code: "1376",
		reducedCode: "1.376",
		name: "FGTS",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.04",
		code: "3718",
		reducedCode: "3.718",
		name: "FGTS - Multa Rescisória",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.05",
		code: "13018",
		reducedCode: "13.018",
		name: "Pró-Labore",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.06",
		code: "3715",
		reducedCode: "3.715",
		name: "Salários e Ordenados - PJ",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.07",
		code: "3716",
		reducedCode: "3.716",
		name: "Décimo Terceiro Salário",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.08",
		code: "3717",
		reducedCode: "3.717",
		name: "Férias",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.09",
		code: "1374",
		reducedCode: "1.374",
		name: "Demissões",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.04.99",
		code: "3711",
		reducedCode: "3.711",
		name: "INATIVO - Uniformes",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "37143",
	},
	{
		classification: "1.03.07.05",
		code: "37144",
		reducedCode: "37.144",
		name: "IMPOSTOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "137",
	},
	{
		classification: "1.03.07.05.01",
		code: "1378",
		reducedCode: "1.378",
		name: "IRRF s/ salários",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37144",
	},
	{
		classification: "1.03.07.05.02",
		code: "1377",
		reducedCode: "1.377",
		name: "INSS s/ colaborador",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37144",
	},
	{
		classification: "1.03.07.10",
		code: "3710",
		reducedCode: "3.710",
		name: "SAÚDE OCUPACIONAL",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "137",
	},
	{
		classification: "1.03.07.10.01",
		code: "37101",
		reducedCode: "37.101",
		name: "Serviços de Saúde Ocupacional",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3710",
	},
	{
		classification: "1.03.07.10.03",
		code: "37111",
		reducedCode: "37.111",
		name: "Materiais de Proteção e Uniformes",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3710",
	},
	{
		classification: "1.03.07.10.04",
		code: "37112",
		reducedCode: "37.112",
		name: "INATIVO - Materiais de Proteção e Uniformes C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "3710",
	},
	{
		classification: "1.03.07.10.05",
		code: "3712",
		reducedCode: "3.712",
		name: "INATIVO - EPIs",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "3710",
	},
	{
		classification: "1.03.07.10.99",
		code: "37102",
		reducedCode: "37.102",
		name: "INATIVO - Serviços de Saúde Ocupacional C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "3710",
	},
	{
		classification: "1.03.07.14",
		code: "3714",
		reducedCode: "3.714",
		name: "ACORDO TRABALHISTAS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "137",
	},
	{
		classification: "1.03.07.14.01",
		code: "37141",
		reducedCode: "37.141",
		name: "Acordos Trabalhistas e Indenizações",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3714",
	},
	{
		classification: "1.03.07.14.02",
		code: "37142",
		reducedCode: "37.142",
		name: "INATIVO - Acordo Trabalhistas C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "3714",
	},
	{
		classification: "1.03.08",
		code: "138",
		reducedCode: "138",
		name: "DESPESA: TAXAS E TARIFAS",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.08.01",
		code: "1381",
		reducedCode: "1.381",
		name: "CONTRIBUIÇÃO",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "138",
	},
	{
		classification: "1.03.08.01.01",
		code: "13811",
		reducedCode: "13.811",
		name: "Contribuição a Entidades de Classe",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1381",
	},
	{
		classification: "1.03.08.01.02",
		code: "13812",
		reducedCode: "13.812",
		name: "Contribuição Sindical",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1381",
	},
	{
		classification: "1.03.08.01.03",
		code: "13813",
		reducedCode: "13.813",
		name: "Associação de Classe",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1381",
	},
	{
		classification: "1.03.08.01.04",
		code: "1382",
		reducedCode: "1.382",
		name: "Fust/Funtel",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1381",
	},
	{
		classification: "1.03.08.02",
		code: "1385",
		reducedCode: "1.385",
		name: "TAXAS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "138",
	},
	{
		classification: "1.03.08.02.01",
		code: "13851",
		reducedCode: "13.851",
		name: "Taxas Municipais",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1385",
	},
	{
		classification: "1.03.08.02.02",
		code: "13852",
		reducedCode: "13.852",
		name: "Taxas Estaduais",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1385",
	},
	{
		classification: "1.03.08.02.03",
		code: "13853",
		reducedCode: "13.853",
		name: "Taxas Federais",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1385",
	},
	{
		classification: "1.03.08.02.04",
		code: "13854",
		reducedCode: "13.854",
		name: "Taxas de Expediente",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1385",
	},
	{
		classification: "1.03.08.02.05",
		code: "1383",
		reducedCode: "1.383",
		name: "Tarifas Boletos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1385",
	},
	{
		classification: "1.03.08.02.06",
		code: "1384",
		reducedCode: "1.384",
		name: "Tarifas e pacotes bancários",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1385",
	},
	{
		classification: "1.03.09",
		code: "139",
		reducedCode: "139",
		name: "DESPESA: TERCEIROS",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.09.01",
		code: "1391",
		reducedCode: "1.391",
		name: "SERVIÇOS EMPRESAS TERCEIRIZADAS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "139",
	},
	{
		classification: "1.03.09.01.01",
		code: "13911",
		reducedCode: "13.911",
		name: "Serviços de Consultoria",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1391",
	},
	{
		classification: "1.03.09.01.02",
		code: "13912",
		reducedCode: "13.912",
		name: "INATIVO - Serviços de Consultoria C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1391",
	},
	{
		classification: "1.03.09.01.03",
		code: "13913",
		reducedCode: "13.913",
		name: "Serviços Prestados PJ - Cooperativas",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1391",
	},
	{
		classification: "1.03.09.01.04",
		code: "13914",
		reducedCode: "13.914",
		name: "Serviços Prestados c/Retenção Previdenc.",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1391",
	},
	{
		classification: "1.03.09.01.05",
		code: "13915",
		reducedCode: "13.915",
		name: "Serviços Contábeis",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1391",
	},
	{
		classification: "1.03.09.01.06",
		code: "13916",
		reducedCode: "13.916",
		name: "Serviços Jurídicos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1391",
	},
	{
		classification: "1.03.09.01.07",
		code: "13917",
		reducedCode: "13.917",
		name: "Serviços Gráficos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1391",
	},
	{
		classification: "1.03.09.02",
		code: "1392",
		reducedCode: "1.392",
		name: "TERCEIRIZAÇÃO DE SERVIÇOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "139",
	},
	{
		classification: "1.03.09.02.01",
		code: "13921",
		reducedCode: "13.921",
		name: "Serviços Prestados - PJ",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1392",
	},
	{
		classification: "1.03.09.02.02",
		code: "13922",
		reducedCode: "13.922",
		name: "Serviços Prestados - PF",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1392",
	},
	{
		classification: "1.03.09.02.03",
		code: "13923",
		reducedCode: "13.923",
		name: "INATIVO - Serviços Prestados - PF C",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "1392",
	},
	{
		classification: "1.03.10",
		code: "1310",
		reducedCode: "1.310",
		name: "DESPESA: TI",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.10.01",
		code: "37145",
		reducedCode: "37.145",
		name: "DESPESAS: TI",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1310",
	},
	{
		classification: "1.03.10.01.01",
		code: "3101",
		reducedCode: "3.101",
		name: "Computadores e Periféricos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37145",
	},
	{
		classification: "1.03.10.01.02",
		code: "3103",
		reducedCode: "3.103",
		name: "INATIVO - Equipamentos de Informática",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "37145",
	},
	{
		classification: "1.03.10.01.03",
		code: "3104",
		reducedCode: "3.104",
		name: "Infraestrutura de Datacenter",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37145",
	},
	{
		classification: "1.03.10.02",
		code: "3106",
		reducedCode: "3.106",
		name: "SISTEMAS E APLICAÇÕES",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "1310",
	},
	{
		classification: "1.03.10.02.01",
		code: "31061",
		reducedCode: "31.061",
		name: "Softwares",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3106",
	},
	{
		classification: "1.03.10.02.02",
		code: "31062",
		reducedCode: "31.062",
		name: "INATIVO - Serviços de Informática",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "inativo",
		parentCode: "3106",
	},
	{
		classification: "1.03.10.02.03",
		code: "31063",
		reducedCode: "31.063",
		name: "Telefonia - STFC",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3106",
	},
	{
		classification: "1.03.10.02.04",
		code: "3102",
		reducedCode: "3.102",
		name: "INATIVO - Direito de Uso Software",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "inativo",
		parentCode: "3106",
	},
	{
		classification: "1.03.10.02.05",
		code: "3105",
		reducedCode: "3.105",
		name: "INATIVO - Segurança de Dados",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "inativo",
		parentCode: "3106",
	},
	{
		classification: "1.03.11",
		code: "13011",
		reducedCode: "13.011",
		name: "DESPESA: UTLITIES",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.11.01",
		code: "37146",
		reducedCode: "37.146",
		name: "DESPESA: UTLITIES",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13011",
	},
	{
		classification: "1.03.11.01.01",
		code: "3111",
		reducedCode: "3.111",
		name: "Água e Esgoto",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37146",
	},
	{
		classification: "1.03.11.01.02",
		code: "3112",
		reducedCode: "3.112",
		name: "Energia Elétrica (Lojas, Escritorios)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37146",
	},
	{
		classification: "1.03.11.01.03",
		code: "3113",
		reducedCode: "3.113",
		name: "INATIVO - Link de Internet",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "inativo",
		parentCode: "37146",
	},
	{
		classification: "1.03.11.01.04",
		code: "3114",
		reducedCode: "3.114",
		name: "Telefone",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37146",
	},
	{
		classification: "1.03.12",
		code: "13012",
		reducedCode: "13.012",
		name: "DESPESA: VEÍCULOS",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.12.01",
		code: "37147",
		reducedCode: "37.147",
		name: "DESPESA: VEÍCULOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13012",
	},
	{
		classification: "1.03.12.01.01",
		code: "3121",
		reducedCode: "3.121",
		name: "IPVA",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37147",
	},
	{
		classification: "1.03.12.01.02",
		code: "3124",
		reducedCode: "3.124",
		name: "Multas e Infrações",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37147",
	},
	{
		classification: "1.03.12.01.03",
		code: "3125",
		reducedCode: "3.125",
		name: "Seguro de Veículos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37147",
	},
	{
		classification: "1.03.12.03",
		code: "3123",
		reducedCode: "3.123",
		name: "MANUTENÇÃO DE VEÍCULOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "13012",
	},
	{
		classification: "1.03.12.03.01",
		code: "31231",
		reducedCode: "31.231",
		name: "Manutenção Preventiva de Veículos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3123",
	},
	{
		classification: "1.03.12.03.02",
		code: "31232",
		reducedCode: "31.232",
		name: "Manutenção Corretiva de Veículos",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3123",
	},
	{
		classification: "1.03.12.03.03",
		code: "3122",
		reducedCode: "3.122",
		name: "Lavagem",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "3123",
	},
	{
		classification: "1.03.13",
		code: "1301",
		reducedCode: "1.301",
		name: "DESPESA: INDENIZAÇÕES",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13",
	},
	{
		classification: "1.03.13.01",
		code: "13001",
		reducedCode: "13.001",
		name: "INDENIZAÇÕES",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1301",
	},
	{
		classification: "1.03.13.01.01",
		code: "13002",
		reducedCode: "13.002",
		name: "Indenizações",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13001",
	},
	{
		classification: "1.04",
		code: "14",
		reducedCode: "14",
		name: "IMPOSTOS",
		planType: "S",
		level: 2,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.04.01",
		code: "141",
		reducedCode: "141",
		name: "IMPOSTOS: DEDUÇÕES",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "14",
	},
	{
		classification: "1.04.01.01",
		code: "1411",
		reducedCode: "1.411",
		name: "FEDERAIS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "141",
	},
	{
		classification: "1.04.01.01.01",
		code: "14111",
		reducedCode: "14.111",
		name: "COFINS - Não Cumulativo",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1411",
	},
	{
		classification: "1.04.01.01.02",
		code: "14112",
		reducedCode: "14.112",
		name: "COFINS - Cumulativo",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1411",
	},
	{
		classification: "1.04.01.01.03",
		code: "14151",
		reducedCode: "14.151",
		name: "Pis - Não Cumulativo",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1411",
	},
	{
		classification: "1.04.01.01.04",
		code: "14152",
		reducedCode: "14.152",
		name: "Pis - Cumulativo",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1411",
	},
	{
		classification: "1.04.01.01.05",
		code: "1416",
		reducedCode: "1.416",
		name: "INSS Receita Bruta",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1411",
	},
	{
		classification: "1.04.01.02",
		code: "1415",
		reducedCode: "1.415",
		name: "ESTADUAIS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "141",
	},
	{
		classification: "1.04.01.02.01",
		code: "1412",
		reducedCode: "1.412",
		name: "ICMS",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1415",
	},
	{
		classification: "1.04.01.02.02",
		code: "1413",
		reducedCode: "1.413",
		name: "ICMS dif aliq.",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1415",
	},
	{
		classification: "1.04.01.03",
		code: "37151",
		reducedCode: "37.151",
		name: "MUNICIPAL",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "141",
	},
	{
		classification: "1.04.01.03.01",
		code: "1414",
		reducedCode: "1.414",
		name: "ISS",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37151",
	},
	{
		classification: "1.04.02",
		code: "142",
		reducedCode: "142",
		name: "IMPOSTOS: PARCELAMENTO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "14",
	},
	{
		classification: "1.04.02.01",
		code: "37152",
		reducedCode: "37.152",
		name: "PARCELAMENTO FEDERAIS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "142",
	},
	{
		classification: "1.04.02.01.01",
		code: "1421",
		reducedCode: "1.421",
		name: "COFINS parcelamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37152",
	},
	{
		classification: "1.04.02.01.02",
		code: "1422",
		reducedCode: "1.422",
		name: "CSLL parcelamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37152",
	},
	{
		classification: "1.04.02.01.03",
		code: "1424",
		reducedCode: "1.424",
		name: "IRPJ parcelamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37152",
	},
	{
		classification: "1.04.02.01.04",
		code: "1425",
		reducedCode: "1.425",
		name: "PIS parcelamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37152",
	},
	{
		classification: "1.04.02.02",
		code: "37153",
		reducedCode: "37.153",
		name: "PARCELAMENTO ESTADUAL",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "142",
	},
	{
		classification: "1.04.02.02.01",
		code: "1423",
		reducedCode: "1.423",
		name: "ICMS parcelamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37153",
	},
	{
		classification: "1.04.03",
		code: "143",
		reducedCode: "143",
		name: "IMPOSTOS: RETENÇÃO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "14",
	},
	{
		classification: "1.04.03.01",
		code: "37154",
		reducedCode: "37.154",
		name: "FEDERAIS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "143",
	},
	{
		classification: "1.04.03.01.01",
		code: "1431",
		reducedCode: "1.431",
		name: "CSLL/PIS/COFINS (retenção)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37154",
	},
	{
		classification: "1.04.03.01.02",
		code: "1432",
		reducedCode: "1.432",
		name: "INSS s/ terceiros",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37154",
	},
	{
		classification: "1.04.03.01.03",
		code: "1433",
		reducedCode: "1.433",
		name: "IRRF s/ Aluguel",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37154",
	},
	{
		classification: "1.04.03.01.04",
		code: "1434",
		reducedCode: "1.434",
		name: "IRRF s/ PJ",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37154",
	},
	{
		classification: "1.04.03.01.05",
		code: "1435",
		reducedCode: "1.435",
		name: "IRRF s/ Serviços",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37154",
	},
	{
		classification: "1.04.04",
		code: "144",
		reducedCode: "144",
		name: "IMPOSTOS: SOBRE RESULTADO",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "14",
	},
	{
		classification: "1.04.04.01",
		code: "1441",
		reducedCode: "1.441",
		name: "CSLL",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "144",
	},
	{
		classification: "1.04.04.01.01",
		code: "14411",
		reducedCode: "14.411",
		name: "CSLL s/ Lucro Presumido",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1441",
	},
	{
		classification: "1.04.04.01.02",
		code: "14412",
		reducedCode: "14.412",
		name: "CSLL s/ Lucro Real",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1441",
	},
	{
		classification: "1.04.04.02",
		code: "1442",
		reducedCode: "1.442",
		name: "IRPJ",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "144",
	},
	{
		classification: "1.04.04.02.01",
		code: "14421",
		reducedCode: "14.421",
		name: "IRPJ s/ Lucro Presumido",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1442",
	},
	{
		classification: "1.04.04.02.02",
		code: "14422",
		reducedCode: "14.422",
		name: "IRPJ s/ Lucro Real",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "1442",
	},
	{
		classification: "1.05",
		code: "15",
		reducedCode: "15",
		name: "DISTRIBUIÇÃO",
		planType: "S",
		level: 2,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.05.01",
		code: "13019",
		reducedCode: "13.019",
		name: "DISTRIBUIÇÃO: DIVIDENDOS",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "15",
	},
	{
		classification: "1.05.01.01",
		code: "37150",
		reducedCode: "37.150",
		name: "DISTRIBUIÇÃO: DIVIDENDOS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13019",
	},
	{
		classification: "1.05.01.01.01",
		code: "13020",
		reducedCode: "13.020",
		name: "Lucros a Pagar (Salários e Dividendos)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37150",
	},
	{
		classification: "1.06",
		code: "16",
		reducedCode: "16",
		name: "CONTA TRANSITÓRIA",
		planType: "S",
		level: 2,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.06.01",
		code: "13023",
		reducedCode: "13.023",
		name: "CONTA TRANSITÓRIA: OUTROS",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "16",
	},
	{
		classification: "1.06.01.01",
		code: "37148",
		reducedCode: "37.148",
		name: "CONTAS TRANSITORIAS",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13023",
	},
	{
		classification: "1.06.01.01.01",
		code: "13024",
		reducedCode: "13.024",
		name: "Repasse a Terceiros (Transitória)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37148",
	},
	{
		classification: "1.06.01.01.02",
		code: "13027",
		reducedCode: "13.027",
		name: "Recurso Operação",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37148",
	},
	{
		classification: "1.06.01.01.03",
		code: "13028",
		reducedCode: "13.028",
		name: "Adiantamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "37148",
	},
	{
		classification: "1.06.01.01.04",
		code: "13029",
		reducedCode: "13.029",
		name: "(-)Devolução de Adiantamento",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "37148",
	},
	{
		classification: "1.06.01.01.05",
		code: "13030",
		reducedCode: "13.030",
		name: "SWAP",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37148",
	},
	{
		classification: "1.07",
		code: "17",
		reducedCode: "17",
		name: "DEDUÇÕES",
		planType: "S",
		level: 2,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.07.01",
		code: "13025",
		reducedCode: "13.025",
		name: "DEDUÇÕES: OUTRAS DEDUÇÕES",
		planType: "S",
		level: 3,
		nature: "D",
		allocation: "N",
		status: "ativo",
		parentCode: "17",
	},
	{
		classification: "1.07.01.01",
		code: "37149",
		reducedCode: "37.149",
		name: "DEDUÇÕES: OUTRAS DEDUCOES",
		planType: "S",
		level: 4,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "13025",
	},
	{
		classification: "1.07.01.01.01",
		code: "13026",
		reducedCode: "13.026",
		name: "Devoluções (Estorno de Clientes)",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37149",
	},
	{
		classification: "1.08",
		code: "18",
		reducedCode: "18",
		name: "AÇÕES",
		planType: "S",
		level: 2,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "",
	},
	{
		classification: "1.08.01",
		code: "181",
		reducedCode: "181",
		name: "AÇÕES PREFERENCIAIS",
		planType: "S",
		level: 3,
		nature: "C",
		allocation: "N",
		status: "ativo",
		parentCode: "18",
	},
	{
		classification: "1.08.01.01",
		code: "37155",
		reducedCode: "37.155",
		name: "ACOES PREFRENCIAIS",
		planType: "S",
		level: 4,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "181",
	},
	{
		classification: "1.08.01.01.01",
		code: "1812",
		reducedCode: "1.812",
		name: "Compra de Ações",
		planType: "A",
		level: 5,
		nature: "D",
		allocation: "S",
		status: "ativo",
		parentCode: "37155",
	},
	{
		classification: "1.08.01.01.02",
		code: "1811",
		reducedCode: "1.811",
		name: "Venda de Ações",
		planType: "A",
		level: 5,
		nature: "C",
		allocation: "S",
		status: "ativo",
		parentCode: "37155",
	},
];

module.exports = { DEFAULT_FINANCIAL_ACCOUNT_PLAN };

